### ISSUE TITLE
Rounding of large (54bit) amounts in Output

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1012]
Currently we use an integer for our amount, but the safety of this is debatable, since JSON numbers are 64 bit floats but integers have only a [53 effective bits](http://www.2ality.com/2012/07/large-integers.html). The effect of this can be seen in `nodejs` and in the browser:

```shell
> JSON.stringify([9007199254740992])
'[9007199254740992]'
> JSON.stringify([9007199254740992 + 1])
'[9007199254740992]'
> 2400000000000000
```

The rounding errors do not always happen, and probably won't happen on our servers. However, we don't have a way to allow clients to guard against these errors.

We could allow string amounts to be submitted, as well as numbers.

Options:

* A: Don't fix
* B: Allow string, but also number of any size
* C: Allow string, disallow numbers beyond a certain size 
* D: Allow only string. `"amount": "1"`, etc.

**Comment by diminator** [comment]
> D: Allow only string. "amount": "1", etc.

:+1:

But realize that if the JSON gets read on a JS client, it shouldnt try to convert it to an `int`

**Comment by ttmc** [comment]
I thought the problem was with _JavaScript_ only supporting integers of 53 effective bits, not just JSON. To handle bigger integers in JavaScript, one would have to encode them as strings (or similar) and use a special library. I know that such libraries must exist, because a lot of crypto requires the ability to work with big integers.

**Comment by r-marques** [comment]
I also think its safer if we allow only strings, not only on the amount but probably in all the fields.

**Comment by libscott** [comment]
What's the issue with allowing integers until a certain amount? For example, 2**50 or 1125899906842624, this gives alot of leeway and most people will never know the difference.

**Comment by ttmc** [comment]
Suppose we do allow them to enter a number rather than a string (in quotes). What will happen if they enter a number that's way too big, like 2**70? Every language has a different way of handling integer overflow. Some throw errors or exceptions. Some peg at MaxInteger. Some store Infinity. Some wrap around...

I'm leaning towards representing the amounts as strings in the JSON representation, and then checking that they're "okay" before converting them to integers internally:
* Is it a sequence of digits?
* Is it small enough? This should be checked _before_ converting it to an int. In Python 3, the maximum-size of an integer is actually system-dependent! (You can find out what it is by checking the value of `sys.maxsize`. On my system, it is 9223372036854775807 which is 2**63 - 1 ). We could just cap it at "9000000000000000000" ('9' followed by 18 zeros) because that's easy to check using string operators: just check the length and each individual digit (if necessary).

**Comment by libscott** [comment]
If they enter a number thats too big (for javascript), we stop it getting written to the database. 

We cant stop users from making mistakes; its entirely possible that most users will model amounts as numbers anyway, and stringify them during transaction assembly. 

If we want to have the best possible chance of protecting people from integer overflows or floating point imprecisions, we should throw an error that warns people not to model their amounts as integers if they submit anything except a string as you describe.

But then they have to think about string validation of unsigned decimals; the alternative being not to allow a number over 2**53-1. 

Im not saying i like one more than the other. One datapoint, usually, a too-big number would be encountered in a CREATE transaction, ie it can be caught before any damage is done. And actually, if we do have an asset amount cap, when a REFILL takes place we would have to validate that the sum of the amounts for this asset is not over the limit, regardless of what our maximum is.
