### ISSUE TITLE
GET /transaction/ID need status flag

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#1038]
Currently it returns all transaction statuses (`backlog`, `undecided`, `valid`)

By default it should only return `valid`

The other statuses should be provided explicitly
`GET /transactions/{tx_id}?status={backlog|undecided}`

also affects the docs #830

**Comment by sbellem** [comment]
> also affects the docs #830

addressed in 22806907a8ef46eddf0d83d22557836f6ac4e3c9

**Comment by sbellem** [comment]
@diminator If a transaction has made it to a valid block, and is also in an undecided block, should a `GET /transactions/txi_id?status=undecided` return the transaction?

**Comment by sbellem** [comment]
Here is a rough outline of some possible behaviours. That being said I strongly advise we work from real use cases to guide the decision making process.

### Return status in response payload
No status query parameter. `GET /transactions/id` returns the transaction if it is in:
* the `BACKLOG`, or
* in an `UNDECIDED` block, or
* in a `VALID` block.

**This requires adding a `status` field in the response payload.**

### Query exactly what the API consumer requests
With a `status` query parameter, such that `GET /transactions/id?status=(backlog,undecided,valid)` will query exactly what is being asked for. This means that if a transaction is both in an undecided and valid block, and an API consumer makes the calls `GET /transactions/id?status=undecided` or `GET /transactions/id?status=valid` in both cases the transaction will be returned.

**This requires a slightly modified version of `core.Bigchain.get_transaction()` that would take `status` as a parameter.**

**Comment by libscott** [comment]
No, it shouldn't. A transaction that is in a valid block and also in an undecided block is valid. That undecided block is in fact no longer valid, since it would contain a double spend.

**Comment by sbellem** [comment]
@libscott What about the case in which a transaction is in the backlog as well as in a valid block and/or undecided block, and GET /transactions/id?status=backlog is requested?

**Comment by libscott** [comment]
I think these questions are outside the scope of this issue, the method `Bigchain.get_transaction` returns the transaction status, which is compared with the status provided by the user.

In which case the question becomes, what should `get_transaction` return as the status if the transaction is in the backlog and also in a block.

For the use case:

1. User posts transaction
1. User requests `/api/v1/transactions/[txid]?status=BACKLOG`
1. User expects to see transaction

The problem here is the user:

* They are racing against the server, which may remove the transaction from the backlog faster than they request it from the backlog, or
* They have posted an already existing transaction and expected it to have status of "BACKLOG"

It's not a particularly legitimate use cases due to these wrong assumptions, though it might be a good idea to clarify this in the docs.

**Comment by sbellem** [comment]
> I think these questions are outside the scope of this issue, the method `Bigchain.get_transaction` returns the transaction status, which is compared with the status provided by the user.

I think we should separate the HTTP API behaviour from the underlying `core` function used to support the desired HTTP API behaviour. In other words, if a particular HTTP API call is needed, then the underlying core needs to provide the function(s) to support the call. That is in contrast to the HTTP API being modelled, constrained, limited, etc by the underlying core function(s) it has been associated with.

With the above in mind I think we should clarify what the HTTP API call in question is meant to be for, e.g., its purpose, possible use cases, etc.

For example, why would an API consumer make the request:

`GET /transactions/id?status=backlog`

**Comment by diminator** [comment]
> As an API consumer it may be more convenient to make the simpler request GET /transactions/id and receive a response that includes the status of the transaction.

In this case you expect to return a (valid) transaction, not a status

the docs will need to clear out what is returned depending on the status flag, so there is some degree of freedom there

**Comment by diminator** [comment]
> the docs will need to clear out what is returned depending on the status flag, so there is some degree of freedom there

Discard this - the transaction resource endpoint only need to return the transaction
If the filter is active (`undecided` or `backlog`) and the transaction is found, then return the transaction
If the transaction occurs multiple times in `undecided` or `backlog` (due to user malfunctioning) then return the transaction once



> As an API consumer it may be more convenient to make the simpler request GET /transactions/id and receive a response that includes the status of the transaction.

Providing metadata together with the resource object is a good suggestion:

```
{
  transaction: {},
  status: {}
}
```

Nevertheless, I think this can be merged afterwards
The `statuses` endpoint still needs to deal with multiple locations of the transaction

**Comment by r-marques** [comment]
Created pr #1360 to fix the documentation in the meantime.

**Comment by TimDaub** [comment]
Decision from discussions with team on #1522 was to follow through with [proposal 2](https://github.com/bigchaindb/bigchaindb/blob/99499b1f8783719a082813912ac9a0d363ae278f/bdb-ip.md#proposal-2-6)

Reasoning:

`POST /transactions/` already returns a `202 Accepted`. According to WC3's status codes:

> The request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place. There is no facility for re-sending a status code from an asynchronous operation such as this.

>The 202 response is intentionally non-committal. Its purpose is to allow a server to accept a request for some other process (perhaps a batch-oriented process that is only run once per day) without requiring that the user agent's connection to the server persist until the process is completed. The entity returned with this response SHOULD include an indication of the request's current status and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled.

During the time the transaction is in BACKLOG, UNDECIDED or recycled due to be included in an INVALID block, we encourage users to check `/status` (or if they're very proficient `/blocks` and `/votes`).

`POST /transactions` now returns a header field pointing to a "status monitor": `/status?transaction_id`.

Additionally, we'll include a note under `POST /transactions` about our preferred workflows. The two being:

- polling for the status of the transaction as shown [here - scroll up to the previous code snipped](https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html#asset-transfer)
- listening to BigchainDB's event API

To close this issue, we need to make the endpoint to everything outlined in this comment.
