### ISSUE TITLE
setup pyup

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1046]
ref: https://pyup.io/

**pyup** could be included as a part of our continuous integration to help us detect whether upgrading a dependency causes problem.

**Comment by sohkai** [comment]
Note: a limitation of pyup is that it only works with requirements files (.txt files; you can configure it to point to any).

Given that (and what setup.py dependencies should be used for), one way we could use pyup is to have it act as a dependency notifier (but never merge any of its autogenerated PRs). We could split our required dependencies into a .txt file, configure pyup to operate on this file, and read it into our setup.py: pyup will then automatically run tests on every update to a dependency. If the tests pass, we can close the PR knowing the new version works fine, otherwise, we can pin our allowed versions to avoid the newer version.

Some manual intervention will still be necessary, as the above wouldn't catch something like our recent issue with pysha-3 (that was a version mismatch between the driver and server; everything still worked independently), but would at least have notified us that a new version was available (and had breaking changes).
