### ISSUE TITLE
Proposal: Recommend server users use Ubuntu 16.04, for now

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1077]
This is just for BigchainDB Server.

We use a variety of operating systems internally, but I think it would be best if we standardized on recommending one for our users, for now, and reflecting that choice throughout our documentation, installation scripts, etc.

In the future, we can explicitly support multiple operating systems, but for now Ubuntu 16.04 is probably sufficient, and if someone wants to use some other Ubuntu version or Linux distro, they can look at the Ubuntu 16.04 stuff and figure out what to do from that. (If they want to use Windows or macOS, we can tell them to use a virtual machine or Docker.)

Today, our docs and code have a mix of Ubuntu 14.04, 16.04 and Fedora stuff. I'd like to clean that up.

If we opt to Dockerize everything (for deployment), then it's fine to have just one OS inside the container, and the Docker machine / host can be running anything that works with Docker.

This is just a proposal that I'm putting out there for comment.

**Comment by r-marques** [comment]
I think its a good a idea to go with only ubuntu 16.04

**Comment by sohkai** [comment]
+1, docker is mainstream enough now that people who want to try running it on bare metal can do so at their own peril.

**Comment by krish7919** [comment]
1. The systemd init scripts will only work on 16.04; 14.04 does not support systemd.
2.  I would not suggest an Ubuntu Xenial docker base image. It has security [vulnerabilities]([link]https://hub.docker.com/r/library/ubuntu/tags/)
3. The bigger the OS, the larger the attack surface and hence to trim down the attack surface, we can use a minimal host OS. And instead of trimming a hefty Ubuntu image, we can start with a host OS like CoreOS or Atomic or Snappy, and then decide on a docker base image with no vulnerabilities. I prefer alpine or busybox, but it varies from case to case.
