### ISSUE TITLE
Possible to create valid block via sybill

### ISSUE THREAD

**Issue by libscott** [bigchaindb/bigchaindb#1168]
[Example](https://github.com/bigchaindb/bigchaindb/commit/39f689e8de95042ef2ee4586ee799d00207ffe04)

Relates to #1166 

Problems:

* Possible to create block listing fake nodes as voters which is then voted VALID, ie, voters don't validate block voter lists against their own voters
* Invalid votes (wrong signature) are counted such that they affect voting outcome, so any node with database access can DOS the system.

Solution:

Block is VALID if:
* Majority (>50%) of ELIGIBLE votes say VALID & agree on previous block
* OR: Dependent (later) block is valid (a vote on a block is an acknowledgement of validity of previous blocks) (this is new)

Vote is ELIGIBLE if:
* Is only vote from node n for block b
* Signature matches pubkey and payload
* Is in block voter list
* Is in federation keyring (this is new)

**Comment by libscott** [comment]
Also possible to DOS system with unauthenticated votes (if you can write to DB)

**Comment by ttmc** [comment]
Unfortunately, there's no such thing as the "federation keyring." It was proposed earlier, but was rejected at that time because it introduces centralization; see issue #436 . I'm open to revisiting the idea.

Regarding the idea of voting a block valid if a dependent later block is valid... it's not clear to me how that later block managed to get voted valid first, before the block upon which its validity depends.

**Comment by ttmc** [comment]
Also, could you add some more explanation of the problem in the issue description?

**Comment by libscott** [comment]
> Also, could you add some more explanation of the problem in the issue description?

Sure

**Comment by ttmc** [comment]
Maybe we can split these two different-but-related issues into two separate issues. The "internal DOS" issue isn't specific to votes. A malicious node could also write lots of invalid blocks to the bigchain table. Maybe create a new issue for "internal DOS" detection & mitigation, if one doesn't exist already.

**Comment by ttmc** [comment]
I had some more thoughts about the problem of a malicious node writing a baloney `voters` list into a block it creates. There are at least two bad things a malicious node can do to the `voters` list in blocks it creates:

* remove legit public keys of the other federation nodes, preventing them from voting on the block
* add fake "sybil" public keys of imaginary federation nodes, for which it has all the corresponding private keys, so it can produce valid votes

While checking the `voters` list against the "federation keyring" is one way to prevent those problems, there are other options. In particular, each node could have a rule something like:

"One condition for this block to get a vote-of-valid from me is that its `voters` list must have more than 85% overlap with _my_ local keyring."

It can't be 100% because we need to allow for nodes to come and go from the federation from time to time, but it will take time for all federation nodes to update their local keyrings.

If we take this approach, we need to re-evaluate how many votes are needed on a block to switch it from undecided to valid/invalid. 50% is probably too low. 66.7% seems like it would suffice. It's not like block validity is a matter of opinion: the usual outcome is that all nodes will agree that a block is valid/invalid. Any disagreement from any node should be a red flag to investigate further.

**Comment by libscott** [comment]
+1 from me. I was thinking something similar but the above states it more clearly.
