### ISSUE TITLE
[tx model] Remove version field

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1175]
This issue proposes to remove the `version` field on the transaction model since the version of the transaction model is currently tightly coupled to that of the server, and the server cannot process different schema versions.

Or perhaps, put in the form of a question: "Could we simplify the transaction payload by removing the version for now since it is tightly coupled to the server version, and the server does not currently handle multiple schema versions?"

Although arguably minimally, this could help in simplifying client code that generate payloads, and would also simplify server code.

**Comment by mgrand** [comment]
I like having a version field. In the post 1.0 future, the transaction format will evolve and it will be unacceptable to just immediately stop being compatible with older clients due to a server upgrade. The only way not to cause a disruption by forcing ever client to upgrade at the same time there is a server update is to have a version field and temporarily support multiple message formats.

**Comment by ttmc** [comment]
From [Scott's blog post about changes to the transaction model in v0.9](https://blog.bigchaindb.com/changes-to-the-transaction-model-in-bigchaindb-server-0-9-ad4e62658b24#.acp7huafk):

"We brought the transaction version down to match the server version, to indicate that it is still subject to changes. When we release server version 1.0, we will decouple the transaction version so that it only changes when we actually change then schema."
