### ISSUE TITLE
Asset containing Python bytes object 

### ISSUE THREAD

**Issue by adarshsaraf123** [bigchaindb/bigchaindb#1228]
Currently, owing to JSON serialization of the transaction `dict` object, we cannot create assets with Python `bytes` object. 

For example, if the `data` field in an Asset contains encrypted data which is a `bytes` object then this asset data will not be JSON-serializable. Hence a create transaction will fail at the point where BigchainDB serializes the transaction data. For a large asset data, Base64 encoding of the encrypted data is a very costly process. 

Is there any support for creating assets containing such `bytes` object without having to encode the bytes object to save on time?

**Comment by libscott** [comment]
Hello,

BigchainDB is not designed to support large binary payloads. For this case it is recommended to hash the content and link to it in another database, such as IPFS or S3. For smaller payloads, base64 serialization is an option. Base64 has approx 40% overhead on storage size.

**Comment by adarshsaraf123** [comment]
Thank you @libscott for your quick reply. 
What are the payload sizes that you are talking about when you say large binary payloads?

**Comment by vrde** [comment]
@adarshsaraf123 the maximum size of a transaction is ~16kb, see #805. /cc @ttmc

**Comment by adarshsaraf123** [comment]
If BigchainDB cannot support larger payloads then what's the point of it supporting petabytes of data as claimed in the whitepaper?  With a transaction size as low as 16kb i cannot even store an audio file

**Comment by ttmc** [comment]
There's a soft limit of 16 kb per transaction (on average) that arises as follows:

1. The underlying database (RethinkDB or MongoDB) has a soft limit on the size of a single document of about 16 MB. See [RethinkDB Limitations](https://rethinkdb.com/limitations/) and [MongoDB Limits](https://docs.mongodb.com/manual/reference/limits/)
2. Blocks are documents and they can contain up to 1000 transactions, so that means there's a soft limit of about 16 kb on the average size of a transaction. Some might be larger, but others will have to be smaller.

**Comment by ttmc** [comment]
The large capacity is needed for handling large throughputs (e.g. from IoT devices) over long periods of time, not large payloads in individual transactions.

In general:
- use file systems to store audio files, images, movies.
- use databases to store/index/query structured and semi-structured data.

**Comment by adarshsaraf123** [comment]
@ttmc Thank you for the reply.
