### ISSUE TITLE
Transactions reassigned forever

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1241]
Scenario:
On a long-running instance of Bigchaindb; running for over 2 days.
Transactions were being create at the rate of 1 every 5 secs.
These are general transactions, nothing custom/fancy.
I do not have a copy of the transaction body now.
If needed, can try to repro and provide additional details.

Stdout:
```
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 0e3fd65d3c6189566939d0a1a93a4674f31b8ff12d5414481fefbc53d8664065
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 63a216fca84b16d5792e3b5ae46db1efe7e6abcf53e17407a3e3ea0ca564c585
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 9b9acbac31e4e2ec0049e0ccdb77f59a7e173a6d6a1343564fb4efe587233af2
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 3511085c265002984627fd4a9a80254136c8c6717ee067899bb51d7d8d376e62
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 27ba9b31b33e96ef9666cc03703fe233c9d4d6f4ce20c1fa760be9fa987056c0
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 0e3fd65d3c6189566939d0a1a93a4674f31b8ff12d5414481fefbc53d8664065
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 63a216fca84b16d5792e3b5ae46db1efe7e6abcf53e17407a3e3ea0ca564c585
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 9b9acbac31e4e2ec0049e0ccdb77f59a7e173a6d6a1343564fb4efe587233af2
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 3511085c265002984627fd4a9a80254136c8c6717ee067899bb51d7d8d376e62
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 27ba9b31b33e96ef9666cc03703fe233c9d4d6f4ce20c1fa760be9fa987056c0
INFO:bigchaindb.pipelines.stale:Reassigning transaction with id 0e3fd65d3c6189566939d0a1a93a4674f31b8ff12d5414481fefbc53d8664065
```

**Comment by ttmc** [comment]
The basic problem is that the backlog is being treated as an unbounded queue, and additional resources aren't deployed as-needed. Some potential solutions:

1. A user don't want to wait forever for their transaction to get into a block, so just delete transactions that have been waiting longer than, say, 120 seconds. In other words, instead of reassigning stale transactions, just delete them from the backlog.
2. Put a cap on the size of the backlog, so that any new transactions coming to a "full" backlog would be rejected.
3. Detect when the backlog is getting full and allocate more resources to block-building, akin to what was proposed in issue #791.

**Comment by r-marques** [comment]
I don't think this is a problem with resources if we are only creating a transaction every 5 seconds but I do need more details to be able to reproduce this.

**Comment by ttmc** [comment]
BigchainDB 2.0 comes out soon and it doesn't have any concept of reassigning transactions. It works quite differently. This issue becomes a non-issue, do it deserves to be closed forever.
