### ISSUE TITLE
Decouple transaction from asset

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#1275]
# Proposal
This document explores the benefits in decoupling asset and transaction, and proposes a simple technical solution to implement it.

## Current implementation

In the [current implementation](https://docs.bigchaindb.com/projects/server/en/latest/data-models/transaction-model.html) of BigchainDB the asset is embedded inside the transaction model.

```json
{
    "id": "<hash of transaction, excluding signatures (see explanation)>",
    "version": "<version number of the transaction model>",
    "inputs": ["<list of inputs>"],
    "outputs": ["<list of outputs>"],
    "operation": "<string>",
    "asset": "<digital asset description (explained in the next section)>",
    "metadata": "<any JSON document>"
}
```

`asset` can have one of the following schemas:
 - if `operation` is `CREATE`, then
```json
{ "data": "<json document>" }
```
 - if `operation` is `TRANSFER`, then
```json
{ "id": "<asset's CREATE transaction ID (sha3-256 hash)>" }
```

## Decoupling transactions and assets
This proposal is to move the `asset` **outside** the transaction model to store it in another collection, and to make it content addressable. In the transaction model, `asset` will just contain the hash of the actual asset.

Moreover, decoupling transaction and asset makes a clear distinction between the permissioning layer (handled by *conditions* and *fulfillments* with *Crypto Conditions*) and the data layer. Think about it this way:
 - Each document in the new `assets` collection is just the asset as you would store it in a regular database.
 - The `bigchain` collection contains all the metadata (permissioning, provenance, auditing, and more) about the digital asset.

Note: in this proposal, when issuing a `CREATE` transaction, including the asset is considered **optional**.

## Benefits
Decoupling unlocks some interesting features for BigchainDB, specifically:
 - New assets can be `CREATE`d without revealing the content of the asset.
 - Because of the previous point, we can enable the tracking of private payloads in the blockchain: since no content is revealed, a user can encrypt it and share it off–chain, while the original hash can still be used to verify that the shared content is the expected one.
 - Since the asset is not stored in the `block` model anymore, it can be **removed** from BigchainDB without breaking the chain of hashes.
 - The content of the asset is not buried in `block['block']['transactions'][<index>]['asset']` since it would live in its own collection, hence it's simpler to write queries).
 - To improve queryability (and indexes) and speed we can even decide to store specific kind of payloads in different collections :1st_place_medal:

# Implementation

## Transaction model
The only difference in the transaction model is for the `asset` key. Instead of holding the value of the asset, it holds the hash of the asset.

```json
{
    "id": "<hash of transaction, excluding signatures (see explanation)>",
    "version": "<version number of the transaction model>",
    "inputs": ["<list of inputs>"],
    "outputs": ["<list of outputs>"],
    "operation": "<string>",
    "asset": "<hash of the asset>",
    "metadata": "<any JSON document>"
}
```
At this point, both `CREATE` and `TRANSFER` operations will just point to the hash of the asset, so there is no need to separate the two using `data` or `id`.

## API
`POST`ing data:
- The API should expose a new endpoint to upload assets. An endpoint will store the asset if and only if there is a valid `CREATE` transaction `tx` where `tx['asset'] == hash(asset)`.
- The API might extend the current [`POST /api/v1/transactions`](https://docs.bigchaindb.com/projects/server/en/v0.9.3/drivers-clients/http-client-server-api.html#post--api-v1-transactions) to accept a *transaction* and an *asset* together, to simplify the UX.

`GET`ting data:
- Symmetrically, the API should expose a new endpoint to download assets.
- Symmetrically, the API should expose a new endpoint to get a *transaction* and an *asset* together.

# :woman_astronaut: Advanced ideas :woman_astronaut:

![mind-blown](https://cloud.githubusercontent.com/assets/134680/23855872/bb5c4c40-07f7-11e7-9798-5262a5d6424c.gif)

## Using `CID`s
What if I told you that `asset` in the transaction can be a [CID](https://github.com/ipld/cid)? If so, we 
would be able to manage *binary assets* uploaded to other systems. (Eventually, we can ask @multiformats to add @ipdb to the [`protocols.csv`](https://github.com/multiformats/multiaddr/blob/master/protocols.csv)).

## Different collections with different indexes
To improve queryability, we can have different collections providing different indexes. Let's say we have a collection better suitable for temporal data, another one optimized for full text search. A user might be able to "route" an asset to the preferred collection.

**Comment by sbellem** [comment]
Nice proposal @vrde! 

You may want to explicitly add, under the benefits:

* Increased consistency: only one schema for both `CREATE` and `TRANSFER` operations.

**Comment by ttmc** [comment]
This is a nice idea.

I think the main concern will be that people don't want their data to be deletable without detection. We can of course put safeguards around the data in the new assets collection(s), similar to what we intend for the `bigchain` (blocks) and `votes` collections.

Anyway, not even the blocks have a hash chain, at least not today. Even if they _did_, that wouldn't prevent deletion/modification, it would just provide another way to detect that deletion or modification happened.

Moreover, with this proposal, people would still be able to stuff arbitrary data in the transaction `metadata` (up to some size limit). But querying metadata will probably never be as good as querying it in a special collection with asset-specific indexes (maybe elsewhere).

**Comment by libscott** [comment]
So, does this propose that we introduce a separate table for assets?

This could be problematic because both the bigchain table and the assets table would probably be sharded and you can't join sharded collections.

**Comment by vrde** [comment]
> I think the main concern will be that people don't want their data to be deletable without detection. We can of course put safeguards around the data in the new assets collection(s), similar to what we intend for the bigchain (blocks) and votes collections.

That's a good point.
Quick idea: we can add a flag to a `CREATE` transaction saying that *an asset has been provided together with the transaction*.

> Moreover, with this proposal, people would still be able to stuff arbitrary data in the transaction metadata (up to some size limit). But querying metadata will probably never be as good as querying it in a special collection with asset-specific indexes (maybe elsewhere).

I see `metadata` as something **transaction specific**, so they are not related to asset queryability.

**Comment by libscott** [comment]
I'd say there's a good case for making `transaction.asset` more freeform though, so that it can be a URI.

**Comment by vrde** [comment]
> So, does this propose that we introduce a separate table for assets?

Yes. I should have been more explicit.

> This could be problematic because both the bigchain table and the assets table would probably be sharded and you can't join sharded collections.

What you imply is that there might be a performance issue?

**Comment by libscott** [comment]
If you want to run a query on data that is valid (data in the bigchain table can be invalid) you need to go via the blocks table. So if you want to query asset data for only validated transactions, in a performant way, you should have a fully replicated index of valid blocks (TODO), and join the bigchain table; if you had a separate assets table you would not be able to join it.

**Comment by vrde** [comment]
AFAIK we will have the same limitation when we will shard the `bigchain` table.

**Comment by libscott** [comment]
Not quite, we can query the bigchain table across shards and any _unsharded_ collections (like an index of election results) can be joined.

**Comment by libscott** [comment]
Alternative idea:

Inside the transaction, have a placeholder that can be identified by the hashing algorithm, where rather than hash contents it hashes the hash of the contents. That way, the contents can be replaced by their hash, and the transaction ID doesn't have to change. Ie:

```
tx = {
    "asset": {
        "data": {
            "#SWAP": { [some data here] }
        }
    }
}
```

Which can then become:

```
tx = {
    "asset": {
        "data": {
            "#SWAP": [hash of the data that was here]
        }
    }
}
```

**Comment by r-marques** [comment]
### Workflow

This is a workflow that uses all the features of bigchaindb:

1. Client creates (CREATE) an asset:

The creation process needs to be changed. The client now needs to hash the
asset and include the hash of the asset in the transaction before calculating
the txid and signing the transaction. (this requires changes to how clients
construct transactions)

2. How does the client post the transaction to bigchaindb?

Now the client needs to post 2 documents instead of just one: the transaction
and the asset. (this requires changes to the post transaction endpoint)

Question: Should we allow for for no asset payload? A user wants to store only an hash on bigchaindb and stores the data elsewhere?

3. How are these two decoupled documents stored in the backlog collection?

I guess it would be something like:

```json
{
    "transaction": "<transaction document>",
    "asset": "<asset document | null>",
    "assignee": "...",
    "assignment_timestamp": "...",
}
```

This would require us to possibly update the backlog queries (or maybe
not).

4. Transaction validation changes:

The transaction validation should do an additional check to make sure the asset
hash is correct. So the transaction validation would have the
asset as an optional parameter and check its hash.

6. Changes to the pipelines:

The logic of the block and voting pipelines would have to change a bit.
The block pipeline would have to unpack the transaction and
asset from the document in 3) and if the transaction validation passes also
store the assets.

This may be an early optimization but the best way to do it would be to store
all of the assets after the block has been written (bulk write for better
performance). This way if something goes wrong with the block pipeline and a
block is not written then we don't write assets for transactions that do not
exist. On the other hand the pipelines are critical and should never fail. 

For the voting pipeline once it gets the block to vote on it would have to
retrieve all the assets belonging to the transactions in that block to validate
the hash block (this would only have to be done for CREATE transactions).

7. How should the asset be stored and how it should map to the transaction that
   created it:

There are two asset attributes that can be used to index it and map it to the
transactions: `id` the transaction id that created the asset, and `hash` the
value that will be in all transactions related to this asset. We can use any of
these attributes or both.

```json
{
    "id": "<txid of the CREATE transaction that created the asset>",
    "hash": "<the asset hash>",
    "asset": "<the actual asset document>"
}
```

The `id` provides a direct mapping between the asset and transaction that
created it. This makes it easier to check if the transaction is valid without
having to first search for the `CREATE` transaction whose asset hash is `hash`.
And since `txids` should be unique we can make this index unique to make sure
that there are no duplicate/multiple assets for the same transaction.

The `hash` allows us to retrieve all the transactions related to an asset.

8. Changes to GET transaction database queries.

I can think of 3 solutions:

- 8.1: insert the asset in the transaction (only CREATE or both)

Do two queries to get the asset and the transaction and in the transaction
replace the asset hash with the actual asset. Since the schema for CREATE and
TRANSFER are now aligned with @vrde proposal we can do this for both CREATE and
TRANSFER transactions.

When validating, signing or hashing always swap the asset document with the
hash.

This would not change the api, just the backend logic for the queries.

- 8.2: return the asset separately (only CREATE or both)

Do two queries to get the asset and the transaction and return both separately.

This requires changes to both the backend logic and the api.

- 8.3: don't return the asset at all

Simply return the transaction as is and do not return the asset. The asset can
be queried separately (by hash and/or CREATE txid) by the client. This way we
keep both asset and transaction api separate.

We have been talking for a while in having an asset api to make BigchainDB feel
more like a database and less like a blockchain. This would be a good
opportunity to start doing that. BigchainDB can guarantee that we only return
assets from valid transactions but if a client still wants the check it can
still retrieve the transactions related to the asset.

This would require no changes to the transaction api. We would need to change
the backend queries for the assets.

**Comment by vrde** [comment]
> Now the client needs to post 2 documents instead of just one: the transaction
> and the asset. (this requires changes to the post transaction endpoint)

If we want to keep everything in a single `POST` we can have something like:

```json
{
    "id": "<hash of transaction, excluding signatures (see explanation)>",
    "version": "<version number of the transaction model>",
    "inputs": ["<list of inputs>"],
    "outputs": ["<list of outputs>"],
    "operation": "<string>",
    "asset": "<document|hash|null>",
    "metadata": "<any JSON document>"
}
```

So we basically allow the client to:
 - Embed the asset document to the transaction (we will take care of calculating the `sha256` and replace the document with the hash).
 - Use only the hash of the asset if they want to keep it secret (this partially answers your question I copy pasted below).
 - `null` if the asset is empty.

> Question: Should we allow for for no asset payload? A user wants to store only an hash on bigchaindb and stores the data elsewhere?

IMO it makes sense. We can even add an (optional) schema to support other content addressable networks, like IPFS.

> Changes to GET transaction database queries.
> 8.1: insert the asset in the transaction (only CREATE or both)

I this this is the best approach, so we keep backward compatibility. We can do it for both `CREATE` and `TRANSFER`.

**Comment by r-marques** [comment]
> Embed the asset document to the transaction (we will take care of calculating the sha256 and replace the document with the hash).

This can be how the client submits the transaction. But when the client is building the transaction it needs to calculate the hash and use that to calculate both the txid and the signature. It cannot be done only server side. I am afraid that there will a lot of hashing and replacing that will just make things confusing.

> IMO it makes sense. We can even add an (optional) schema to support other content addressable networks, like IPFS.

Yes this a point that was mentioned in the initial proposal. My opinion is that instead of overloading the transaction model with this we can add it at the asset level. So the transaction does create and asset and then the asset is just a pointer to ipfs for instance.

**Comment by vrde** [comment]
> This can be how the client submits the transaction. But when the client is building the transaction it needs to calculate the hash and use that to calculate both the txid and the signature. It cannot be done only server side. I am afraid that there will a lot of hashing and replacing that will just make things confusing.

IMO it's not adding too much confusion.

> Yes this a point that was mentioned in the initial proposal. My opinion is that instead of overloading the transaction model with this we can add it at the asset level. So the transaction does create and asset and then the asset is just a pointer to ipfs for instance.

:+1:
