### ISSUE TITLE
Revisit timestamps?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#132]
Right now, there are timestamps in several places:
- Each transaction gets a timestamp from the client who submitted it
- Each block gets a timestamp from the BigchainDB server process (Python) which generated it
- Each vote gets a timestamp from the BigchainDB server process (Python) which generated it

We can't trust the timestamps from clients, so why bother having them at all? If they want to include a timestamp from a [trusted timestamping](https://en.wikipedia.org/wiki/Trusted_timestamping) service (along with a signature from that service), then they can include that in the transaction payload.

Or maybe we could allow clients the option of sending timestamps from a trusted timestamping service (plus associated signature and maybe other metadata, such as the name of the service)?

We should also reconsider the timestamps generated by the BigchainDB servers. It's generally a bad idea to pretend that all the clocks in a distributed system are trustworthy or synchronized (unless you've gone to a lot of trouble, like what Google's [Spanner](https://en.wikipedia.org/wiki/Spanner_%28database%29) does). Unfortunately, users of BigchainDB might not know that, and they might believe the timestamps _mean_ something. Maybe just remove those timestamps?

**Comment by ttmc** [comment]
We may sometimes be able to trust client-provided timestamps, at least for figuring out transaction ordering, because the client has an incentive to get their transactions in the proper order-by-timestamp.

**Comment by ttmc** [comment]
Two more notes on timestamps:
* Even if we don't get rid of timestamps, we should have documentation and UI to help users interpret them properly.
* If we ran a time-synchronization daemon on all BigchainDB servers (and there are many options, e.g. `ntpd`, `tlsdate`), then that would bring them into better (but not perfect) time synchronization with each other and with global time servers. Don't get too excited: this increases cost, complexity and attack surface.

**Comment by ttmc** [comment]
Related: Issue #349 

Some interesting ideas from there:

* The idea of using the median of the vote timestamps (which come from multiple nodes). That could be used to replace transaction and block timestamps (i.e. only votes would have timestamps).
* Assign a timestamp to a transaction when it first arrives at BigchainDB based on the median timestamp from all (or many) federation nodes.

**Comment by ttmc** [comment]
There was some discussion about timestamps on the internal Slack dev channel today. Some of the discussion:

Rodolphe: we can add timestamp verification to the consensus
actually it would be simpler and more performant if we only added timestamp verification for blocks
the timestamps are already being generated in UTC so as long as a majority of the nodes knows how to confgure the time in their machines we should be ok

Troy: NTP only gets you something like +/- hundreds of ms

Rodolphe: for 99 % of use cases min precision should be ok

Tim: I agree
so if we can come up with something that gives me the approx. time a block was created I can trust then that's already a big win

Rodolphe: that shouldn't be difficult

Troy: Anyway, we need to be careful about how that timestamp gets used and interpreted. Definitely need error bars.

**Comment by ttmc** [comment]
Just to clarify some of the ideas in the last comment:

* Explain to users how to _interpret_ timestamps, i.e. don't trust them too much, use them as a general guide. There are _many_ timestamps one can look at surrounding a valid transaction:  the timestamps on all the other transactions in the same block, the timestamp of its block, and the timestamps of the votes on its block. That's a lot of timestamp information (from many different nodes); it can be used to make statistical types of inferences.

* Add an optional consensus plugin which checks the timestamp on a block, as part of block validity checking. When a node votes on that block, it will check the timestamp of the block against its own local clock, and if they differ too much, the block is voted invalid.

**Comment by ttmc** [comment]
We now have a good page of documentation about timestamps (including how to interpret them) at https://docs.bigchaindb.com/en/latest/timestamps.html

I will close this issue; we can open a new one if we have a new specific timestamp-related idea, feature, or bug.

**Comment by libscott** [comment]
Reopening for consideration, as part of #798 I am wondering what kind of validation to add to the transaction timestamps, and having looked through the code and talked to people it seems like there is every reason to remove them:

* Not used in the code, correct order depends on transaction dependency graph and not client provided timestamp.
* Should not be used in the code, since client provided timestamps cannot be trusted, and we create our own when we do need them (tx backlog priority). 
* Ambiguous meaning, see page: https://docs.bigchaindb.com/en/latest/timestamps.html
* Maintenance overhead, see page: https://docs.bigchaindb.com/en/latest/timestamps.html
* Ambiguity on what the data field *should* be, currently unix epoch in seconds, but milliseconds or a trusted timestamp service provided value are also legitimate candidates
* Amounts to hand-holding of the user, when the user could very well put the timestamp in the `metadata` field if they so wished.

The only possible value I can see to them being there is for operational analysis, ie, extracting a set of possible client latencies, but it's not clear _who_ this will benefit either.
