### ISSUE TITLE
Run mongodb monitoring and backup agents as non-root user

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1424]
`USER mongodb-mms-agent ` in Dockerfile for both backup and monitoring agents.
Will need dir and file permission changes in entrypoint script and Dockerfile.

**Comment by muawiakh** [comment]
We need to modify the read permissions on the secrets and allow
the `mongodb-mms-agent` to read the credentials. Alternative approach is to change the `readOnly` permissions from mounted volumes `/etc/mongod/cloud` and `/etc/mongod/ssl` and make `mongodb-mms-agent` the owner of the above mentioned directories in the `entrypoint` script but I went with the earlier approach because changing readOnly on the volumes might be such a good idea.

**Comment by ttmc** [comment]
@muawiakh Can this issue be close now?

**Comment by muawiakh** [comment]
Yes.
