### ISSUE TITLE
Cost Associated with BigchainDB?

### ISSUE THREAD

**Issue by sugandhasingla** [bigchaindb/bigchaindb#1448]
Hi Team
I am new to blockchain and bigchainDB. Currently I am exploring the possibility of building a platform using the bigchainDB. I have some questions which I am having trouble finding the answers for. Could use some help. Thanks

Ques1: Is there a cost to running the database? This could be a direct monetary cost or our cost comes in the form of us using computational time for other databases?

Ques2: What are the security implications of using Bigchain?

Ques3: What are the challenges when we scale up?

Ques4: Do we need to setup multiple nodes? Are we sharing nodes with strangers who’ve setup separate databases? How does that work?

**Comment by r-marques** [comment]
Hi @sugandhasingla 

> Ques1: Is there a cost to running the database? This could be a direct monetary cost or our cost comes in the form of us using computational time for other databases?

There are two ways to run/use BigchainDB. BigchainDB can be used for private deployments in which case federation members would need handle the costs of running a BigchainDB node or use a public deployment of BigchainDB like [IPDB](https://ipdb.foundation/) in which case there may be fees associated with using the service.

> Ques2: What are the security implications of using Bigchain?

BigchainDB was designed to to run under a federated model in which a majority of the nodes need to reach a consensus about the validity of a given transaction.

> Ques3: What are the challenges when we scale up?

BigchainDB was designed to scale horizontally similar to other distributed databases so to scale up you would need to add more nodes to the federation.

> Are we sharing nodes with strangers who’ve setup separate databases? How does that work?

That depends on the governance layer of the federation. With BigchainDB all the federation nodes need to be known and their public keys and other attributes shared so that a cluster can be correctly setup.

> Ques4: Do we need to setup multiple nodes?

Ultimately BigchainDB can be run with a single node, that is a typical development environment but for the sake of fault tolerance and decentralization you will want a multi node deployment.

More information about the BigchainDB architecture can be found in the [whitepaper](https://www.bigchaindb.com/whitepaper/)

**Comment by TimDaub** [comment]
@sugandhasingla: We also have internal calculations on how much it would cost to run BigchainDB etc..
In general, this sounds like an opportunity to have a call. Please feel free to send me an email to tim@bigchaindb.com and we'll make it happen.

**Comment by sugandhasingla** [comment]
@TimDaub : Sure, would love to have a call with you guys.

**Comment by inzakone** [comment]
> @r-marques thx for the detailed answer :)
> @sugandhasingla: We also have internal calculations on how much it would cost to run BigchainDB etc..
> In general, this sounds like an opportunity to have a call. Please feel free to send me an email to [tim@bigchaindb.com](mailto:tim@bigchaindb.com) and we'll make it happen.

Hi Tim, your mail id is not Working! Might you please provide a working one!? Thanking You.

**Comment by ttmc** [comment]
@inzakone Tim wrote that in May of 2017 and he has gone on to pursue other exciting opportunities since then.

To run a single BigchainDB node, all you need is a single VM running all the components (BigchainDB Server, Tendermint, MongoDB, maybe NGINX, etc.). That can be quite low cost. But of course a proper BigchainDB network should have at least four nodes, all run by different entities. That way one node can fail arbitrarily and the network will continue to work properly. And a true production network would have more than four nodes, each with an operator who knows what they're doing (e.g. a DevOps person).

**Comment by inzakone** [comment]
Hi TTMC, thank you for for prompt reply. We got a specific requirement, we would like to use your hosted BigChainDB Service. We will have at least 10 to several nodes extra apart from your BigChainDB hosted service. How much could this cost to us? Thanking you.

**Comment by inzakone** [comment]
Hi TTMC, thank you for for prompt reply. We got a specific requirement, 
we would like to use your hosted BigChainDB Service.
Let say for instance like in a client(nodes outside BigchainDB hosted 
network) server scenario way.
We are planning the implementation of a web application.
How much could this cost to us? Thanking you.

**Comment by akkolwalkar** [comment]
are these problems still relevant or have things improved now?
