### ISSUE TITLE
[travis-fails] docs building issue: Unknown option passed to Flask-CORS: headers

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1478]
```bash
Warning, treated as error:

Unknown option passed to Flask-CORS: headers

ERROR: InvocationError: '/home/travis/build/bigchaindb/bigchaindb/.tox/docsserver/bin/sphinx-build -W -b html -d /home/travis/build/bigchaindb/bigchaindb/.tox/docsserver/tmp/doctrees . /home/travis/build/bigchaindb/bigchaindb/.tox/docsserver/tmp/html'

___________________________________ summary ____________________________________

ERROR:   docsserver: commands failed
```

/cc @vrde @TimDaub just in case you have a clue :smile:

**Comment by ttmc** [comment]
The basic problem is that `CORS()` takes the list of kwargs documented here:

http://flask-cors.corydolphin.com/en/latest/api.html#extension

Our call to `CORS()` (added by PR #1311) includes the kwarg `headers`:
```python
    app = Flask(__name__)

    CORS(app,
         headers=(
             'x-requested-with',
             'content-type',
             'accept',
             'origin',
             'authorization',
             'x-csrftoken',
             'withcredentials',
             'cache-control',
             'cookie',
             'session-id',
         ),
         supports_credentials=True)
```
Unfortunately, `headers` isn't one of the normal kwargs expected by `CORS()`, so we get the warning, "Unknown option passed to Flask-CORS: headers". Warnings don't normally cause a fail, but they do when we build the docs, which is why this only shows up when building the docs.

@diminator You can probably fix this fairly easily. The code in question came from you, so you know what you were aiming to achieve. Right now, this problem is a real pain because it's causing Travis to fail on all new pull requests. (Travis builds the docs as one of its tests.)

**Comment by vrde** [comment]
I'm on it.
