### ISSUE TITLE
Improve HTTP API documentation

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#149]
We need to say on the documentation in which port the api is running and we need instructions on how to change the host. Right now it runs by default in `localhost`.

@vrde How do you change the host so that the API can be accessed remotely?

**Comment by ttmc** [comment]
I changed the docs to reflect the current status of the HTTP API (i.e. not remotely accessible), but the docs will have to be updated once remote access is sorted out. 

@vrde - I'm going to assign this to you because I think you're the most familiar with it, and it's related to Issue #142 where you are already assigned.

**Comment by vrde** [comment]
Fixed in #183! :)
