### ISSUE TITLE
Kubernetes Secrets Management: Create a common secret for ca.pem

### ISSUE THREAD

**Issue by krish7919** [bigchaindb/bigchaindb#1509]
#1497 has a common `ca.pem` for many modules to access the same CA certificate info in the `secrets.yaml` file.
Proposal is to separate it into a separate Kubernetes Secret and let each pod refer to this common secret.

Pros: Easy management and configuration of pods.

Cons: We cannot use different CAs for different modules. Also, best practices dictate that we shouldn't share secrets.

For our use case, we can use a common secret as it's the same data that is shared between pods.
Plus it is `ca.crt`, which is the _public_ key anyway.

We can do something similar for `crl.pem` too.

**Comment by ttmc** [comment]
This proposal arose from two comments in the review of pull request #1497:

Comment 1:  https://github.com/bigchaindb/bigchaindb/pull/1497#pullrequestreview-40984136

Comment 2:  https://github.com/bigchaindb/bigchaindb/pull/1497#pullrequestreview-40985394

In comment 2, I suggested moving both `ca.pem` and `crl.pem` into one new Secret named `ca`, because the CA's public key and the CA's CRL are both CA-related things.

As noted above, this would make it impossible to get the four MongoDB certificates from two or more different CAs. I don't see that as a big problem. Right now, the assumption is that all MongoDB certificates get signed by the CA associated with the organization managing the cluster, i.e. there's just one MongoDB CA per cluster.

**Comment by ttmc** [comment]
It occurred to me that there is (potentially) at least one other CA: the CA who signs the SSL certificate so that access to the HTTP API is via SSL/TLS. There may be more CAs. The CA discussed above is the one associated with MongoDB auth.

Therefore I would amend this proposal as follows:

* Create a new Secret named `mdb-ca` or `mdb-auth-ca` (i.e. the MongoDB auth CA).
* Move two Secret data items into `mdb-ca`:
    1. `ca.pem` (which could be renamed `mdb-ca.pem`) and
    2. `mdb-crl.pem` (which already has a good name!)

**Comment by ttmc** [comment]
One more note: the documentation currently calls the directory associated with the "MongoDB auth CA" `bdb-cluster-ca`, in the page `ca-installation.rst`.

**Comment by ttmc** [comment]
Note: In `secret.yaml`, in the Secret named `bdb-certs`, there's an item named `crlfile`. That item can be removed since it's the same as what's in `mdb-crl.pem`.

**Comment by muawiakh** [comment]
Creating a common secret for ca.pem and crl.pem for all MongoDB replica set members and clients. Because all of them need to have a common CA. Don't need to mention mdb* for CA secrets. For reference: [Use x.509 Certificates to Authenticate Clients](https://docs.mongodb.com/manual/tutorial/configure-x509-client-authentication/)

**Comment by ttmc** [comment]
@muawiakh I guess this issue can be closed now?

**Comment by muawiakh** [comment]
Yes.
