### ISSUE TITLE
/statuses?tx_id (all requests having query parameters) return(s) 400 BAD REQUEST when Content-Type: 'application/json` is set

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#1576]
With `Content-Type: 'application/json'` set:

```
{
    "message": "The browser (or proxy) sent a request that this server could not understand."
}
```

without:

```
{
    "message": "Not found",
    "status": 404
}
```

(or returns the status of transaction).

This happens with BDB v0.10.2

Might be related to: https://github.com/flask-restful/flask-restful/issues/510

This might affect all endpoints using query parameters.

**Edit**: Confirmation, it's affecting all endpoints using query params: https://github.com/bigchaindb/bigchaindb/pull/1577/commits/ea157a30bd09bb78dd8d751e5694cbc9c05d1f28

**Comment by TimDaub** [comment]
Might be related to: https://github.com/flask-restful/flask-restful/issues/510

**Comment by TimDaub** [comment]
This might affect all endpoints using query parameters.

**Comment by TimDaub** [comment]
This is a critical issue that already made users give up on driver development: https://gitter.im/bigchaindb/bigchaindb?at=589123aefba5bfea06b258ae

**Comment by r-marques** [comment]
The only solution that I could find would be to explicitly set the location where the argument parser should check for the arguments.

So instead of:
```python
parser = reqparse.RequestParser()
parser.add_argument('tx_id', type=str)
parser.add_argument('block_id', type=str)
```
 Use this:
```python
parser = reqparse.RequestParser()
parser.add_argument('tx_id', type=str, location='args')
parser.add_argument('block_id', type=str, location='args')
```
This will disregard the `content-type` and get the arguments directly from `args` instead of a json body if the client set the content-type to `application/json`

The only problem is that this is not compatible with with `strict=True` in `parse_args`

**Comment by vrde** [comment]
@r-marques I'm trying to understand if it's something we can do at a middleware level.
