### ISSUE TITLE
Move the bigchaindb/nginx_3scale repo under this repo & make edits

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#1588]
Krish and I discussed this in a private channel. The idea is to move the contents of the bigchaindb/nginx_3scale repo under the `k8s/nginx-3scale/` directory in this repo, so it's more like the `k8s/nginx/` directory (and other subdirectories of `k8s/`).

- [x] Merge all outstanding pull requests in the bigchaindb/nginx_3scale repo.
- [x] Move all the files over, so that the new directory structure is similar to `k8s/nginx/`.
- [x] Update the top-level `LICENSES.md` file in this repo to mention another exception: the licensing of things in the `k8s/nginx-3scale/` directory is described by a separate `LICENSE.md` file in that directory.
- [ ] Update the `README.md` file.
- [x] Move any outstanding issues on the bigchaindb/nginx_3scale repo to this repo.

Please keep the old bigchaindb/nginx_3scale repo around. It might be useful. For example, some of the old Lua code for handling both POSTs and GETs might be handy some day.

**Comment by ttmc** [comment]
Maybe also rename `nginx_entrypoint.bash`?

**Comment by muawiakh** [comment]
[Pull request](https://github.com/bigchaindb/bigchaindb/pull/1728) takes care of the following aspects:

- Move all the files over, so that the new directory structure is similar to k8s/nginx/.
- Update the top-level LICENSES.md file in this repo to mention another exception: the licensing of things in the k8s/nginx-3scale/ directory is described by a separate LICENSE.md file in that directory.
- Update the README.md file.(There was no change in the README.md)
- Renaming nginx_entrypoint.bash -> nginx_3scale_entrypoint.bash

Outstanding issues are migrated to bigchaindb/bigchaindb repo. #1725, #1726, #1727 
No pending PRs left on bigchaindb/nginx_3scale.
We can delete the bigchaindbd/nginx_3scale repo we merge the [PR](https://github.com/bigchaindb/bigchaindb/pull/1728).

**Comment by krish7919** [comment]
We should ideally not delete this repo till we are sure that we will never need it.

If and when we roll back the split nginx changes for websocket support, we will need this old code and the associated history.
