### ISSUE TITLE
[docs] Clean up and fix docstrings in common/transaction.py

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1599]
Multiple docstrings do not build, and cause sphinx errors if one tries to build the docs.

**Comment by ttmc** [comment]
We're going to be refactoring that code in the next month or two (starting with [BEP-9](https://github.com/bigchaindb/BEPs/pull/33)) and we might decide to use the docstrings to generate some code library reference docs at that time. If we do, we'll fix the docstrings so that they don't cause Sphinx errors. If we don't, then this is a non-issue. Either way, we don't need this issue sitting around cluttering up the issue list, so I'm closing it.
