### ISSUE TITLE
provide a RESTful API

### ISSUE THREAD

**Issue by MovGP0** [bigchaindb/bigchaindb#17]
in order to use the bigchaindb remotely in a fully language agnostic way, there should be a RESTful interface with JSON as serialization format. 

this way, 3rd party developers can provide wrappers for various programming languages.

**Comment by genecyber** [comment]
+1 Upvote and :heart:

**Comment by ttmc** [comment]
A client-database API/protocol is definitely in our roadmap.

We've talked a bit about the options, including a RESTful API with JSON serialization. Some databases do have an API like that, but JSON wasn't designed to be an easy-to read query language format, so you end up with really convoluted-looking queries-as-JSON.

Most application developers shouldn't be thinking about the client-database API anyhow; they should be working with the API presented by their language-specific SDK/driver, which should follow the conventions of their programming language. Because of that, the client-database API is somewhat irrelevant to application developers, so long as it can do everything it should do.

Anyway, there are pros and cons to the various choices and we're happy to discuss them.

**Comment by MovGP0** [comment]
usually the queries are not in JSON format. only the response from the server is. 

queries are usually done with the [Open Data Protocol](http://www.odata.org/) (OData) or something similar.

**Comment by Mec-iS** [comment]
GraphQL also seems to be quite popular now. Or maybe a CRUD **JSON-RPC API** with different endpoints mapping to a query builder that runs the query based on passed arguments.

**Comment by ttmc** [comment]
We had an internal discussion about this today and the client-server API will indeed be RESTful with JSON as the serialization format. @vrde will start by documenting the API using Apiary; everyone can then review that.

**Comment by ttmc** [comment]
@MovGP0 @genecyber @Mec-iS please take a look at PR #102 - it adds a RESTful API and is currently under review. It will probably be merged sometime today. The comments there mention stuff that is deferred until later.

https://github.com/bigchaindb/bigchaindb/pull/102

There is also some documentation of the new API at http://docs.bigchaindb.apiary.io/#

**Comment by vrde** [comment]
I just merged the PR. There are still features missing. Some of them are [here](https://github.com/bigchaindb/bigchaindb/issues?q=is%3Aissue+is%3Aopen+label%3Arest-api).
