### ISSUE TITLE
Exception in _connect(): localhost:27017: [Errno 111] Connection refused (MainProcess - pid: 19041)

### ISSUE THREAD

**Issue by AdityaKadmawala** [bigchaindb/bigchaindb#1742]
Hi,
I am using ubuntu 16.04
completed all the steps successfully  unto H as mentioned in the link provided ,
https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html

Now running the blockchaindb start facing the following error
![screenshot from 2017-09-06 04-53-38](https://user-images.githubusercontent.com/19280618/30075083-4428efec-9263-11e7-87f8-f00dff5a0f8b.png)
![screenshot from 2017-09-06 04-54-14](https://user-images.githubusercontent.com/19280618/30075084-442f8334-9263-11e7-8e2c-2679ef6a3434.png)

Thank you in advance.

**Comment by ttmc** [comment]
I think maybe the Quickstart instructions have changed since the "Latest" version in the docs. Maybe try the "master" version of the Quickstart, at:

https://docs.bigchaindb.com/projects/server/en/master/quickstart.html

If that doesn't help, then I need to see what you did _before_ you did `bigchaindb start`. You can copy text from the Terminal application: just select all the text, right-click it, and select Copy. Or press CTRL + SHIFT + C

To paste it here just put three backticks (like \` ) before the text you paste, and three backticks after the text you paste.

**Comment by AdityaKadmawala** [comment]
Its working now,Thanks a lot!
Actually I missed starting the mongodb i.e step D.

Pardon me for my foolish mistake
