### ISSUE TITLE
Delete assets

### ISSUE THREAD

**Issue by Chuseuiti** [bigchaindb/bigchaindb#1774]
Is it possible to delete or expire assets from BigchainDB as the owner of the asset? lets assume that these assets not exist anymore in the outside world or are meaningless

**Comment by r-marques** [comment]
We do not provide a way to delete assets.
Deleting assets would invalidate the chain since you would be changing past blocks.

**Comment by ttmc** [comment]
In the simplest case, an asset has amount 1 (i.e. it's not divisible) and the current owner(s) can create a TRANSFER transaction which transfers it to a public key whose associated private key is unknown (or purposefully forgotten).

Since it's practically impossible to determine the private key that goes with the (known) public key, the asset is effectively frozen forever, unspendable. In the blockchain world, this is known as "burning."

You could even put some notes in the TRANSFER transaction's metadata, saying something like "note": "burning"

More generally, you can burn any output (each of which has an associated asset and amount). To burn an entire divisible asset with initial amount greater than 1, you'd have to burn all the unspent outputs associated with that asset.

**Comment by TimDaub** [comment]
Thx @ttmc and @r-marques for those excellent answers.
@Chuseuiti, we've implemented a "burn" operations on a BDB client already.

Here is a tutorial: https://tutorials.bigchaindb.com/crab/
