### ISSUE TITLE
configure command backend arg is ignored when env var is set

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1833]
_description will be added soon_

**Comment by ttmc** [comment]
According to:

https://docs.bigchaindb.com/projects/server/en/latest/server-reference/configuration.html

The value of each BigchainDB Server configuration setting is determined according to the following rules:

- If it’s set by an environment variable, then use that value
- Otherwise, if it’s set in a local config file, then use that value
- Otherwise, use the default value
