### ISSUE TITLE
Change description to "BigchainDB is a blockchain database"

### ISSUE THREAD

**Issue by msutherl** [bigchaindb/bigchaindb#1889]
### Description

Since it's not accurate to call BigchainDB "scaleable", change the description of this repository to "BigchainDB is a blockchain database".

**Comment by ttmc** [comment]
I don't want to get into the technical details of why this is or isn't a good idea. I just want to note that:

* If you look at the home page https://www.bigchaindb.com/ you will see "The scalable blockchain database powering IPDB" in big lettering at the top.
* In the HTML head tag of that page, you'll see `<meta name="description" content="The scalable blockchain database powering IPDB.">`
* If you look at the official BigchainDB Twitter account at https://twitter.com/BigchainDB then you will see the following in the profile in the left sidebar: "The scalable blockchain database"

I could go on. This issue is proposing a change to the BigchainDB tagline, something which was intended to get BigchainDB to show up in searches for `scalable blockchain`. If you want to change the tagline, you need to coordinate with marketing.

**Comment by TimDaub** [comment]
I'm supporting to change the tagline, but I second this:

> If you want to change the tagline, you need to coordinate with marketing.
