### ISSUE TITLE
update tx model to v2.0

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#1907]
**after issue #1891/#1899**

- [x] update tx model to v2.0
- [x] add error message for tx model v1.0

**Comment by ttmc** [comment]
Just a reminder: "update tx model to v2.0" should include updating the names of the three JSON Schema files for transactions, and the `__init__.py` script, all of which are in the `bigchaindb/common/schema/` directory. The only line to change in `__init__.py` is the one that currently reads:
```python
TX_SCHEMA_VERSION = 'v1.0'
```

**Comment by sbellem** [comment]
> updating the names of the three JSON Schema files for transactions

Out of curiosity, why do we include the version number in the file name?

**Comment by ttmc** [comment]
> Out of curiosity, why do we include the version number in the file name?

I did that so it would be obvious (to humans) what version of the transaction model that that particular JSON Schema file was for. It also makes it easy to load the right JSON Schema file for the job, without Python (or any programming language) having to open the file to look around inside it just to figure out what version of the transaction model it's to be used for validating.

I guess an alternative would be to use numbered subdirectories. For example, all the JSON Schema files for validating transaction schema version 1.0 could go in `bigchaindb/common/schema/transactions/1.0/`

**Comment by sbellem** [comment]
I am a bit confused. Do we plan to have multiple files pointing to different versions, under the same BigchainDB version?

**Comment by ttmc** [comment]
In the future, BigchainDB Server will have to be able to validate transactions of several versions (because examples of all versions will be stored in the blockchain). For example, maybe transactions of versions 2.0, 2.1, 2.2, 3.0, 3.1, 4.0 and 5.0 will all be present. Therefore JSON Schema files will have to be available for doing schema validation of all those different transaction versions.

Or maybe not... Maybe the latest BigchainDB Server can only validate transactions of the latest transaction version, and _other software_ (e.g. for auditors) can validate transactions going all the way back?

It seems to me that BigchainDB Server software should be able to independently verify the entire blockchain (i.e. every transaction) on its own. It might want to do that, for example, when it's a newly-added node in a network that has been around for a long time.
