### ISSUE TITLE
College Project Implementing BigChainDB

### ISSUE THREAD

**Issue by davidtalan** [bigchaindb/bigchaindb#1910]
Hey guys, for my college project, I am thinking of creating a web application that will be using BigChainDB as the database. I would be using BigChainDB to store healthcare records and use the web app to access it and display said records. I'm just wondering if using BigChainDB would be appropriate for this project and if you guys could point me towards the right direction on how to get it started.

**Comment by ttmc** [comment]
I guess it depends on what kind of data you intend to store.

- Many healthcare records are sensitive personal data. Such data is often the subject of strong regulations.
- Blockchains are typically publicly-readable.
- Data stored in blockchains is not usually deletable. It's "immutable."
- Even if data is stored encrypted, what if some "bad guy" steals the decryption key and publishes it for all the world to see? What if someone develops an algorithm or quantum computer that cracks the encryption? You can't delete the data.
- What if someone wants their data deleted, and government regulation requires you to comply?

In summary, blockchains are good for storing some kinds of important public data that you don't want lost, but not other kinds of data. Think copyright claims, land titles, public council meeting minutes, measurements of the sea level at station 143b, etc.

If you want to write records to a live public BigchainDB network that you can use before you graduate, then consider the following. The IPDB Test Net runs BigchainDB and is up and running, but it wipes its data from time to time (because it's just a test net, a place for users to experiment). If that's okay with you, then see https://ipdb.io/   . We're starting to get the IPDB Production Net (with "forever storage") going with one user at a time, slowly. I don't expect it to  be publicly available (to all who ask) any time soon.

**Comment by davidtalan** [comment]
Thank you very much for the reply. I'll definitely check IPDB out. 

My project partner and I only wanted to demonstrate that blockchain can be used as a valid, secure database for healthcare records and our project proposal was accepted with this idea. Keep in mind that since it's only a college project, we won't be going as far as using actual medical records.
