### ISSUE TITLE
Non Deterministic assignment of transactions in S is a DoS vulnerability

### ISSUE THREAD

**Issue by AFDudley** [bigchaindb/bigchaindb#20]
listing 3 line 8 on page 24 of the white paper is:
i ∼ U ({0 , 1 , . . ., k -1 , k +1 , . . ., N -1}) # Stochastic . Any
node but k avoids duplicate vote .

This means that if the same transaction is sent to two nodes, most of the time it will be placed into S twice, one of those entries will be rejected from C. This is a DoS vector.

If I can find the place in the actual source that handles this I will mention it.

**Comment by r-marques** [comment]
This will not be a problem if the txid of the transactions are the same because at the datastore level we use the txid as the primary key to mitigate problems like this.

In case that we have a duplicated transaction in S, before creating a block a node will have to validate the transaction and at this point one of them will make it into C and the other will be flagged as a double spend.

To further mitigate such an attack we could still check for the existence of the transaction in both S and C before accepting the transaction.

**Comment by AFDudley** [comment]
That sounds good. Where is this described in the white paper? I'm looking at the source, and the checks for txid are here:
https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L223

and here:
https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L277

They both refer to 'bigchain'.

but the problematic insert is here and to 'backlog':
https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L205

With the random assignment:
https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L196

If the assignment is instead based on the user-definable fields, this issue goes away. But then something like Cassandra's VNodes will be required to keep the distribution of keys balanced.

I am looking at the code and i'm a bit confused by these checks.

tx contains a timestamp, so shouldn't a transaction that has the same user-defined fields actually get a different timestamp and in turn a different txid?

get_spent is by id, not user-defined content.

validate_transaction never seems to check if all the fields that can be duplicated in a tx are, it's also unclear to me if that's even an invalid tx. So it still looks to me that I could send multiple txs with the same user-defined fields and increase the load of the system by getting them into 'backlog'. I'm also increasing the load by forcing a unique id search on 'bigchain' that I as the attack know will fail, assuming these transactions are even invalid... which again, is unclear.

I am not trying to send anyone fishing, I can make a PR if this is actually an issue. If I am wrong can you please explain why? Thanks!

**Comment by r-marques** [comment]
You are right, regarding validating the transaction before writing it to the 'backlog'.
We do not enforce it in the code or mention it on the withepaper (which we need to).

One of the important parts missing from the code that are in the roadmap is the external api which clients will use to send transactions to bigchaindb nodes.
What we assume is that a bigchaindb node will validate the transaction before writing it to the 'backlog'. This is not enforced at this point.
We could enforce the validation of the transaction in https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L179 but we want to decouple io  and cpu intensive operations so that we can off load them to workers, for performance reasons.

Regarding duplicated transactions with the same hash ('id'), rethinkdb prevents us from writing two documents with the same primary key and since hashes resemble random numbers they will be evenly distributed between the nodes.

Regarding the timestamp, right now it is true that it can be used to create duplicated transactions with a different hash. We should maybe consider not hashing the timestamp. The timestamp right now is only used to provide some ordering in the backlog (a node should start processing old transactions first).

Regarding the validation of the transaction we do check if the input in the transaction was already used before.

**Comment by AFDudley** [comment]
Okay, most of this makes sense to me.

> What we assume is that a bigchaindb node will validate the transaction before writing it to the 'backlog'. This is not enforced at this point.

How can this be BFT if only one node sees any given incoming transaction?

> We could enforce the validation of the transaction in https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/core.py#L179 but we want to decouple io and cpu intensive operations so that we can off load them to workers, for performance reasons.

Yep, makes sense.

> Regarding duplicated transactions with the same hash ('id'), rethinkdb prevents us from writing two documents with the same primary key and since hashes resemble random numbers they will be evenly distributed between the nodes.

Yes, but my point is since the nonce/timestamp of the transaction is being hashed, this is actually undesirable behavior. So it will need to be made up for with something like VNodes.

> Regarding the validation of the transaction we do check if the input in the transaction was already used before.

I think this is a terminology issue on my part, apologies, but is 'input' the only user-definable field in a transaction? I assume some of the other 5 are user-definable as well?

**Comment by r-marques** [comment]
> How can this be BFT if only one node sees any given incoming transaction?

Correct answer would be that bigchaindb is still not BFT.
A client talks / pushes its transaction to one  bigchaindb node. If the node is acting maliciously it can just drop transactions. In this case a client could just try another node.
What would you suggest in this situation?

> think this is a terminology issue on my part, apologies, but is 'input' the only user-definable field in a transaction? I assume some of the other 5 are user-definable as well?

There is the `payload` field on the transaction. We make no assumptions on how the user defines its digital asset. This would allow you create duplicated transactions with a different hash and this could be a source for a DoS. Now I am not sure if this should be handled on the bigchaindb core ( I don't think it should). It should probably be handled at the api level where we can use normally used techniques to detect such behavior and block or rate limit it.

**Comment by AFDudley** [comment]
> If the node is acting maliciously it can just drop transactions. In this case a client could just try another node.
What would you suggest in this situation?

Assuming non-federation members are submitting transactions, the requirements to detect this type of misbehavior are:
1. Proof a valid transaction was submitted to a given node.
2. The given node failed to accept the transaction.

Then, the federation could detect and punish misbehaving nodes. To fix this, the non-federation-submitter would have to present the transaction to a quorum of nodes (3 can detect 1 fault). Then, the other members of that quorum can generate proofs and blame accordingly. (The transaction would also need to contain the IDs of the nodes in the quorum.)

If federation members are submitting transactions they should be able to have only their ID in the quorum and not send them to two other nodes.

**Comment by AFDudley** [comment]
> It should probably be handled at the api level where we can use normally used techniques to detect such behavior and block or rate limit it.

Agreed.

**Comment by vrde** [comment]
BigchainDB 2.0 integration with Tendermint will get rid of this problem. The round-based approach elects a different leader per round, and the leader proposes what's in the block.
