### ISSUE TITLE
how the bigchaindb is incentived?

### ISSUE THREAD

**Issue by benqethan** [bigchaindb/bigchaindb#2011]
Is there incentive to host a node? seems there is no coin/token attached to the bigchaindb. Any plan to scale it any way?

**Comment by ttmc** [comment]
Case A: The incentive to host a node is the same incentive as AWS has to host an EC2 instance for some paying customer. They make some profit (= usage fees - expenses).

Case B: The node host hosts the node as a service for their community, maybe because that's their mandate as an organization. Like how Wikimedia Foundation hosts the servers for Wikipedia.

Case C: Some retired professor has piles of money from some lucky stock investment and is looking for some way to spend it all before he dies.

There are many other cases.
