### ISSUE TITLE
Data missing from node after restart

### ISSUE THREAD

**Issue by danielrea** [bigchaindb/bigchaindb#2027]
* BigchainDB version: 1.2.0
* Operating System: Ubuntu 17.10
* Deployment Type: `Other`
  * For every other type of deployment, please specify the documentation/instructions
  you are following.
https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html

* BigchainDB driver: `[yes]`
  * If using a driver please specify, driver type `[js]`
  and version.
JS 0.3.0

### Description

We had setup a solution with a single node on Ubuntu on an Azure virtual machine to collect data through this node for a client, we had no issues up until recently. Had tested restarting mongo and bigchaindb before and had no data loss. We had left the solution with the client for 2 weeks and came back to discover the node had crashed, upon restart of the node this time the data that we had been collecting has now vanished or at least is no longer accessible by bigchaindb.

### Steps to Reproduce
Commands used to restart node: 
sudo mkdir -p /data/db
sudo chmod -R 700 /data/db
sudo mongod --replSet=bigchain-rs
bigchaindb start

### Logs
The client believes the last time they accessed the data successfully was around 1/25. But in case something may have happened earlier I have attached the full error and normal logs.
Error Log:
https://drive.google.com/file/d/1u-Ww2DRmhDJK8hEtjrNbp-opyV8YA521/view
Log:
https://drive.google.com/open?id=1K_T5MPawvphQ0Lhj4Twlu5PwB1Auu1Go

### Questions
So we are looking to get a solution to this as soon as possible so first off:
1) Is it possible to recover the data that appears to be missing from bigchaindb now?
2) How can we avoid something like this happening in future?

Thanks for your attention please let me know if I can get you any more environmental information.

**Comment by muawiakh** [comment]
From the logs, I can see that you are unable to establish the connection between MongoDB and BigchainDB. That is probably because of MongoDB instance crashing/dying:

```
....
bigchaindb.backend.exceptions.ConnectionError: localhost:27017: [Errno 111] Connection refused
```

In our production deployment templates, we use [MongoDB Cloud Manager](https://www.mongodb.com/cloud/cloud-manager) i.e. Monitoring and Backup agents to monitor and take snapshots of the MongoDB ReplicaSet. You can check out our template and how to configure and recover from the MongoDB Cloud Manager here:

- [Production deployment template](https://docs.bigchaindb.com/projects/server/en/latest/production-deployment-template/node-on-kubernetes.html)
- [Configure MongoDB Cloud Manager for Monitoring and Backup](https://docs.bigchaindb.com/projects/server/en/latest/production-deployment-template/cloud-manager.html)
- [Restore Data from MongoDB Cloud](https://docs.bigchaindb.com/projects/server/en/master/production-deployment-template/restore-from-mongodb-cloud-manager.html)

The documentation mentioned above, is used for our Production deployment template which uses Kubernetes. For your use case, I can see that you only have a single instance hosted on Azure and you are using the [basic quickstart guide](https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html). Simplest solution would be to take periodic back ups of the MongoDB `/data/db` directory and if you have `/data/configdb` take periodic back up of that as well. If you face an issue like this again, you can simply replace it with an older snapshot.

I hope this helps.

**Comment by danielrea** [comment]
Thank you for the quick response Muawiaki.

Without having previously saved backups of /data/db and /data/configdb before is it safe to assume that previous data is now lost?

Thanks

**Comment by muawiakh** [comment]
Yes, because the only place that data persisted was `/data/db` on your Azure virtual machine. IF that is gone, then I am afraid, it is lost.
