### ISSUE TITLE
Hook BigchainDB into ILP five-bells-demo

### ISSUE THREAD

**Issue by diminator** [bigchaindb/bigchaindb#215]
Relates to #201 

WIP

**Comment by r-marques** [comment]
I think it would be nice if we could just replace their sql database in the demos with bigchaindb

**Comment by r-marques** [comment]
The [PAYS-platform](https://github.com/bigchaindb/PAYS-platform) demo is related to this.
We are not exactly replacing their sql database with bigchaindb but we are using ilp to transfer assets between the five-bells ledger and bigchaindb.

Since this issue was opened we have created several examples using bigchaindb https://github.com/bigchaindb/bigchaindb-examples

@diminator what should we do with this issue? Closed it and point to the [PAYS-platform](https://github.com/bigchaindb/PAYS-platform)  demo?

**Comment by sohkai** [comment]
@diminator does https://github.com/bigchaindb/bigchaindb/issues/489 supersede this?

**Comment by diminator** [comment]
closed as duplicate of #489
