### ISSUE TITLE
bigchaindb.readthedocs.org/en/stable/ is outdated

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#216]
compare https://bigchaindb.readthedocs.org/en/stable/

with http://bigchaindb.readthedocs.org/en/master/

**Comment by ttmc** [comment]
ReadTheDocs can render multiple versions and make them all available online. Their documentation about version-handling is at: http://docs.readthedocs.org/en/latest/versions.html

* "stable" means the highest-numbered version (commit tag), which is currently "v0.1.5"
* "latest" points to a branch that we can set in the ReadTheDocs admin. Currently "latest" points to "master" but we could change that.
* "master" means the current master branch. We can make docs for _any_ branch visible online. We could make the docs for the "crazy-experimental-feature-2789" branch available if that branch existed. 

We can also change where our base ReadTheDocs URL points. Right now it points at "stable". Is that bad? A `pip install bigchaindb` will always get the latest `bigchaindb` package from PyPI, which should always be the same as the highest-numbered-version.

I get the sense that the labels "stable" and "latest" are ambiguous, causing a lot of confusion. (They are ReadTheDocs conventions.) Maybe we should just make those labels invisible? I could make it so that "v0.1.5" and "master" are the only options, with "v0.1.5" being at the root URL. Maybe that would clarify what's what.

**Comment by r-marques** [comment]
From what I see the most common is for the URL to point to latest

**Comment by ttmc** [comment]
Yes, from the ReadTheDocs documentation:

"When a user hits the root URL for your documentation, for example http://pip.readthedocs.org/, they will be redirected to the Default version. This defaults to latest, but could also point to your latest released version [stable]."

I changed the Advanced Settings in ReadTheDocs so that the root URL redirects to the docs in the latest (master) branch.

**Comment by ttmc** [comment]
I also went in and made it so that there are only two versions (branches) of documentation visible in the options:

* stable (= the commit with the highest-numbered version tag)
* latest (= `master` branch)

**Comment by ttmc** [comment]
Since it's not clear what "stable" means (i.e. Which version number is this documentation for?), I made it so "stable" isn't available anymore, so the two versions (branches) available at https://bigchaindb.readthedocs.org are:

1. latest (= `master` branch)
2. v0.2.0

That will have to be manually adjusted every time we release a new version number, which is a pain, but at least now it is clear what version you're reading the documentation for.

**Comment by r-marques** [comment]
I am good with that. We can change our approach in the future if we need
