### ISSUE TITLE
Missing immutability target because it doesn't have chain of hashes

### ISSUE THREAD

**Issue by trentmc** [bigchaindb/bigchaindb#218]
We want good immutability. It's one of the key benefits of "blockchain" technology. It's even what defines "block chain" in the narrow sense of the word.

Right now we don't have this. Votes point to the hash of a block. They don't point to previous votes. 

To fix: votes point to hash of previous votes. It shouldn't be a hash of all votes (as all votes may never come in), it should only be a hash of enough votes for the block to be decided.

More detail:

Block model is at http://bigchaindb.readthedocs.org/en/master/models.html#the-block-model

A block has four parts:
1) id = hash of (2)
2) block: the main stuff, e.g. all the transactions, etc.
3) signature of (2)
4) the list of votes; each vote includes the hash/id of the previous block

Note how a block's hash does not include the votes, and it's the votes which contain the hashes of the previous blocks.

Each finished block only contains the hash of the previous block, but that never gets bundled up as part of its hash.

**Comment by r-marques** [comment]
We cannot re-hash the block and at block creation time we don't know what the previous block and we have no way of knowing it unless we block the system between each inserted block (this was the initial behavior).

Our solution was not to chain the blocks but only chain the votes

**Comment by ttmc** [comment]
The "traditional hash chain" has something like this happening over time:

* hash(data1)
* hash(data2 + hash(data1))
* hash(data3 + hash(data2 + hash(data1)))
* etc.

so the latest hash depends _all_ previous data.

We don't have that right now, because a vote only contains the hash of the current block and the hash of the previous block (_not including the votes on the previous block_). The information in a block's data section never propagates farther than the votes of the next block.

Suppose we do make votes include the hash of "everything" in the previous block (i.e. the data plus enough votes to get a quorum)... 

The thing is, we can't calculate the hash of the votes in a block until those votes are in (or at least a quorum of them). Votes on subsequent blocks would be held up waiting for that.

There could be a separate process that comes along behind, appending a "hash of the entire previous block", once that's possible (i.e. once the previous block becomes decided / has a quorum of votes). Is that really necessary? I'm not convinced it is. What does it give us that we don't already have (other than looking more like a traditional block chain)?

We already aim to get tamper resistance and practical immutability in several ways. See the soon-to-be-published FAQ which has a section about that.

**Comment by trentmc** [comment]
Re: Our solution was not to chain the blocks but only chain the votes
Of course, it's not currently chaining the votes either.

We discussed this among Trent, Troy, Rodolphe, Alberto. Summary: changefeeds buy us a *lot*, including benefit here: if votes are changed by a malicious node, all the other nodes will hear about it immediately, and it can be reverted. No need to do more.

Therefore, we can close this ticket.

**Comment by ttmc** [comment]
Some more notes:

- We don't chain the votes.
- We don't revert votes, even if malicious. The votes table is supposed to be append-only.
- A hash chain is neither necessary or sufficient for (practical) immutability. It _can_ help with detecting tampering, but so can what _we_ do.
- The main purposes of the hash chain are, as far as I can tell: 1) to have a compact way to summarize the state of the system and 2) in POW systems like Bitcoin, to prevent miners from gaining an advantage by mining a chain of future blocks in parallel.

**Comment by ttmc** [comment]
Above, I wrote:

> A hash chain is neither necessary nor sufficient for (practical) immutability.

### Not Necessary?

There are many examples of immutable things that have no hash chain. Take, for example, the decimal digits of pi: 3.14159... There's no hash chain anywhere yet good luck changing the digits of pi. They're immutable.

### Not Sufficient?

Suppose we have a nice hash chain stored in memory or on a hard drive. Now suppose we heat the whole computer system to 10,000 degrees Celsius for 40 minutes. The stored data is gone, changed beyond recovery forever. The hash chain didn't prevent it.

### But Aren't Hash Chains Useful?

Sure, as tools in a toolbox for building interesting and useful systems. For example, an auditor can use them to detect changes, but other tools would be needed to undo the changes (if possible).
