### ISSUE TITLE
create block timeout parameter is available now?

### ISSUE THREAD

**Issue by xuhuigithub** [bigchaindb/bigchaindb#2276]
Is there a parameter now available like a create block timeout?

**Comment by xuhuigithub** [comment]
Another question is, why does the bigchaindb configure command do not generate the key pair of bigchaindb now?

**Comment by xuhuigithub** [comment]
I use bigchaindb 2.0.0a3 now.

**Comment by xuhuigithub** [comment]
@muawiakh Can you help me?

**Comment by ttmc** [comment]
@xuhuigithub 

> Is there a parameter now available like a create block timeout?

In BigchainDB 2.0, blocks are proposed and managed by Tendermint, not BigchainDB Server. If you look at [the list of Tendermint configuration settings](http://tendermint.readthedocs.io/projects/tools/en/master/specification/configuration.html), there are many that let you control various timeouts, including `timeout_commit`. (The last thing done to a block before it's final is commit.)

> ...why does the bigchaindb configure command do not generate the key pair of bigchaindb now?

Because BigchainDB Server doesn't _need_ a key pair any more. It doesn't have to sign anything. All blocks and votes are created by Tendermint, so it's the one with the key pair.
