### ISSUE TITLE
Problem: Some users need more help with using MongoDB to do queries

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#2315]
We've gotten some feedback about the page about [Querying in BigchainDB](https://docs.bigchaindb.com/en/latest/query.html).

### Ideas for Improvements

Provide some help with _connecting_ to the MongoDB database, for some common setups.

Provide some query examples.

Maybe note that there are many apps that can help you visualize and query the MongoDB database in a user friendly way. We don't promote any particular one. Examples: MongoDB Compass, Studio 3T, Mongo Management Studio, NoSQLBooster for MongoDB, Dr. Mongo

**Comment by manolodewiner** [comment]
I created a simple script some time ago with basic search in MongoDB. Here is the link to the script:
https://github.com/manolodewiner/query-mongodb-bigchaindb/blob/master/queryMongo.js

We also faced an issue querying BigchainDB when it finds more than 490 records with metadata search, so we decided to use querying in MongoDB as well, as you can implement pagination with it. Here is a code example: 

```js
collection.find({ $text: { $search: ' "01/2016" ' } } ).skip(100).limit(10)
   .toArray(function(err, docs) {
   assert.equal(err, null);
   console.log("Found the following records");

   docs.forEach((doc, i) => {
     totalKwh += parseFloat(doc.data.windmill1) + parseFloat(doc.data.windmill2)
     + parseFloat(doc.data.windmill3) + parseFloat(doc.data.windmill4)
     count++
   })
   console.log(docs.length, count,totalKwh)
   client.close();
   })
```
I can elaborate this with more explanations and examples if needed.

**Comment by gautamdhameja** [comment]
Here are a couple of things I had in mind while proposing this,
1. Documentation on the MongoDB collections used by BigchainDB. For example, the assets are in `asset` collection and metadata is in `metadata` collection. The users should know what they are going to query on and how does the underlying database schema look like. This is different from the transaction schema, just to clarify.
2. We can also give pointers on how to create custom indexes on collections. This is advanced level topic but the node administrators can create custom indexes, during deployment, instead of going with the default text search index.

The overall idea is to make the MongoDB database schema and set up more transparent to the users.

**Comment by ttmc** [comment]
Maybe also mention:

There are tools that let you query a MongoDB database using SQL, e.g. 

- https://mongobooster.com/blog/query-mongodb-with-sql/ 
- https://studio3t.com/whats-new/how-to-query-mongodb-with-sql/

**Comment by ttmc** [comment]
Also link to the BigchainDB Blog post with the examples of how to query BigchainDB data using the Mongo Shell and MongoDB Compass. That post hasn't been published yet but I hope to get it published in the next week.
