### ISSUE TITLE
Bigchain.write_transaction changes the transaction passed as argument

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#251]
The `write_transaction` should create a copy of the transaction before modifying it. So that the transaction passed to `write_transaction` is not modified when `write_transaction` adds the assignee field

**Comment by TimDaub** [comment]
There was this ticket: #593
There was also a PR about this #606

Now though, things have changed again. To `write_transaction` a `Transaction` object is passed (not a `dict` anymore).
The response is a modified `dict` including [`assignee` and `assignment_timestamp`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L109). It's being relied on by several modules and I think that's OK.

Additionally, there is [a test](https://github.com/bigchaindb/bigchaindb/blob/master/tests/test_core.py#L99) that's now being skipped.

@r-marques If it's OK, I'll make this ticket about removing the skipped test, so that we can close it.

**Comment by r-marques** [comment]
:+1:
