### ISSUE TITLE
Unable to restart BigchainDB and Tendermint at block height 1

### ISSUE THREAD

**Issue by muawiakh** [bigchaindb/bigchaindb#2518]
## Description

* BigchainDB version: master - (https://github.com/bigchaindb/bigchaindb/commit/9bf09324df1c63b7fbef0b24830deb5bd80b4dae)
* Tendermint version: `0.22.8`
* MongoDB version: `3.6.3`
* OS: `Ubuntu 18.04.1 LTS bionic`

Unable to restart BigchainDB and Tendermint at block height `1` of Tendermint. I get the following errors in BigchainDB logs:

```
[2018-09-05 14:52:11] [ERROR] (bigchaindb.core) Got invalid InitChain ABCI request (time: 1536156417
chain_id: "test-chain-E0e9OT"
consensus_params {
  block_size {
    max_bytes: 22020096
    max_txs: 10000
    max_gas: -1
  }
  tx_size {
    max_bytes: 10240
    max_gas: -1
  }
  block_gossip {
    block_part_size_bytes: 65536
  }
}
validators {
  address: "r;J\001[\375\277\366-\247\242/5\246\362f\312b\214\342"
  pub_key {
    type: "ed25519"
    data: "U\017\277\306\340*\323\301\257%F\013\266\033\022\215\321\311\0160\363\007\276ow\343\323l\r4-\277"
  }
  power: 10
}
) - the chain {chain_id} is already synced. (MainProcess - pid: 6107)
``` 
and the system crashes.

### Steps to reproduce
 
- Install MongoDB
- Install Tendermint
- Install BigchainDB(master-(https://github.com/bigchaindb/bigchaindb/commit/9bf09324df1c63b7fbef0b24830deb5bd80b4dae))
- Run MongoDB + Tendermint + BigchainDB
- Kill Tendermint and BigchainDB
- Restart Tendermint and BigchainDB
``` bash
# automatically start mongodb as well with Ubuntu 18
$ sudo apt install mongodb 
$ curl -fOL https://github.com/tendermint/tendermint/releases/download/v0.22.8/tendermint_0.22.8_linux_amd64.zip
$ unzip unzip tendermint_0.22.8_linux_amd64.zip
$ mv tendermint /usr/local/bin/
$ git clone https://github.com/bigchaindb/bigchaindb.git
$ cd bigchaindb/
$ pip install .
$ tendermint init
$ tendermint node
$ bigchaindb start
$ pkill bigchaindb
$ pkill tendermint
$ tendermint node
$ bigchaindb start
```

### Workaround

- Drop database, reset tendermint
- Once the system is up, commit a transaction to the system and everything recovers normally.

**Comment by Kasunmadura** [comment]
I also experiencing same issue  when i try add new node to cluster...

[2018-12-16 02:47:35] [ERROR] (bigchaindb.core) Got invalid InitChain ABCI request (time: 1544749476
chain_id: "test-chain-0yYkSZ"
consensus_params {
  block_size {
    max_bytes: 22020096
    max_txs: 10000
    max_gas: -1
  }
  tx_size {
    max_bytes: 10240
    max_gas: -1
  }
  block_gossip {
    block_part_size_bytes: 65536
  }
}
validators {
  address: "C\230\331\314\360c\277;\371N\305\014\341\211\r\353\247\\\344\332"
  pub_key {
    type: "ed25519"
    data: "\272\206\262$Y\007jn\217\231\333\300\2762$\334Ph\271\n\224\330\364f\026\232Y\263\3360\276\243"
  }


any idea how we could fix this

**Comment by bogdanstoica35** [comment]
Same problem here when trying to add a node to the cluster

**Comment by BarathKumarDharani** [comment]
How to confirm both node are communicating in Bigchaindb network . could u please help me on this .

**Comment by omieee** [comment]
Hi,
When i am trying to add the second node. I am facing issue, looks like similar to above

Steps:
1. Installed bdb, tendermint
2. Did tendermint init on both machines
3. Created a common genesis file for both
4. Created toml file for both
5. Updated the nodes with new genesis and toml file
6. Ran tendermint node and bigchaindb start (after configuring ip to 0.0.0.0:9984 and ws to 0.0.0.0) on both
7. One node seems starting, but the other didn't following error occured while running bigchaindb start.

![Screenshot from 2020-03-07 16-39-27](https://user-images.githubusercontent.com/18283609/76142305-4eb1fa80-6092-11ea-9d45-b3a49df9ee40.png)

**Comment by Sh4d0wBlade** [comment]
these issues are probably incured by incorrect argument setting in tendermint's config.toml, because logs say that they are invalid ABCI requests. tendermint needs bigchaindb to be its ABCI.

**Comment by abelakponine** [comment]
I was having this same issue when adding new peers but was able to solve it with the following steps.

I realized I was changing the genesis.json file immediately after setting up tendermint which results in this issue on first run.

1. Run <code>tendermint node</code> after setup without changing genesis.json file i.e use the default genesis.json file,
2. you can run: <code>rm -rf ~/.tendermint</code> to delete the old setup, then run: <code>tendermint init</code> to generate a new genesis file
3. Run <code>tendermint node</code> to start the server. This will initialze tendermint with default and genesis.json file.
4. After initial run, stop server
5. Edit config.toml file of new peer node to your taste
6. Now copy the genesis of the main node into genesis.json file of the new peer node and save
7. Run <code>tendermint unsafe_reset_all</code> on new peer node
8. Run <code>tendermint node</code> on new peer node

This worked for me.

If you are having a failed to dail error ...pex etc, this will be because of firewall blocking connection on your machine, ensure to add port 26656 through firewall in your machine and also run <code>ufw allow 26656</code> on ssh
