### ISSUE TITLE
The same transaction posted twice causes HTTP 500

### ISSUE THREAD

**Issue by ldmberman** [bigchaindb/bigchaindb#2521]
When BigchainDB receives a transaction, it does not try to find it in the database but passes it on to Tendermint. When Tendermint detects a duplicate, it does not run either CheckTx or DeliverTx, but reports an error: `Error broadcasting transaction: Tx already exists in cache`.

Duplicates are invalid transactions and have to be reported via HTTP 400.

script to reproduce
```
from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair

bdb_root_url = 'http://localhost:9984'
bdb = BigchainDB(bdb_root_url)

alice, bob = generate_keypair(), generate_keypair()

asset = {'data': {}}
prepared_creation_tx = bdb.transactions.prepare(
            operation='CREATE',
                signers=alice.public_key,
                    asset=asset,
                    )

fulfilled_creation_tx = bdb.transactions.fulfill(prepared_creation_tx,
                                                         private_keys=alice.private_key)

sent_creation_tx = bdb.transactions.send_sync(fulfilled_creation_tx)
sent_creation_tx = bdb.transactions.send_sync(fulfilled_creation_tx)
```

**Comment by shahbazn** [comment]
Is this issue already fixed? I am unable to reproduce in current master branch.

Posting the same transaction correctly returns HTTP 400 response and seems to be doing the validation at server level without even passing transaction to tendermint

**Comment by ldmberman** [comment]
Did you post it in the commit mode? It seems to work in the commit mode indeed.

I can reproduce it in the sync and async modes though.

**Comment by shahbazn** [comment]
The actual issue here is that when we post the same transaction multiple times really quickly so that the first transaction is still in tendermint cache waiting to be processed tendermint returns the following error with HTTP status code 500
```
{'jsonrpc': '2.0', 'id': '445b7b06-179a-4766-87c2-4c3eb02e4606', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'Error broadcasting transaction: Tx already exists in cache'}}
```

This behaviour is correct and expected but it just needs to be logged properly in BigchainDB's logs.

Now if you add few seconds of delay between the last two lines in the script provided above to reproduce the issue, you will notice that the 500 error goes away and you correctly get 400 error response code for duplicate transaction. This happens because now you have given enough time for system to process the first post of the transaction and then when the duplicate is posted the system can identify it as a duplicate.
