### ISSUE TITLE
Upgrading from 2.0.0b9 to 2.0.0

### ISSUE THREAD

**Issue by dolphinsd** [bigchaindb/bigchaindb#2672]
Is there a tutorial or how to in order to upgrade from 2.0.0b9 to 2.0.0 versions?

Thank you.

**Comment by davie-lab** [comment]
Hi. The problem is that beta 9 version uses older version of Tendermint that has incompatible blockchain. As I understand there is no easy way to preserve blockchain after upgrade.
But there is `election new chain-migration` commnd (see [docs](http://docs.bigchaindb.com/projects/server/en/latest/server-reference/bigchaindb-cli.html)). That allows you to instantiate an election to halt block creation for chain migration.

**Comment by dolphinsd** [comment]
not possible, you need to refresh to a new database or use chaining as done on omnibasis
see https://omnibasis.freshdesk.com/support/solutions/articles/36000248286-how-to-connect-blockchain-network

**Comment by zzappie** [comment]
Ha what is this omni thing?
Sorry I think I didn't get the message.  Could you please elaborate a bit on why it is not possible?

**Comment by dolphinsd** [comment]
@zzappie upgrade from 2.0.0b9 to 2.0.0 is not possible, the only way to do it to use blockchain chaining method described by omnibasis, they also implemented it.
