### ISSUE TITLE
Tendermint restart

### ISSUE THREAD

**Issue by hectordufau** [bigchaindb/bigchaindb#2709]
**Describe the bug**
Tendermint shows a error message after restart.

**To Reproduce**
1. Start tendermint
2. Stop tendermint with CTRL + C
3. Run "tendermint node --consensus.create_empty_blocks=false" or "tendermint node"

**Expected behavior**
Run tendermint normally

**Logs or terminal output**
ERROR: Failed to create node: Error during handshake: Error on replay: App block height (124) is higher than core (5)

**Desktop (please complete the following information):**
 - Distribution: Ubuntu 18.04
 - Bigchaindb version: 2.0.dev
 - Tendermint version: 0.31.5-d2eab536
 - Mongodb version: 3.6.3
- Python full version: 3.6.9

**Comment by zzappie** [comment]
Hey @hectordufau thanks for bug report!  I'll make time to investigate it.

**Comment by z3ky** [comment]
I have the same problem using the docker all in one. Stopping the container and starting again produces this error. Only with an unsafe reset I can connect the container to the tendermint network again.

**Comment by z3ky** [comment]
@hectordufau after shutting down tendermint and bigchaindb I delete tendermind/mongodb tendermint/data/blockstore.db evidence.db state.db tx_index.db cs.wal and set all values in priv_validator_state.json to 0. Then I can restart tendermint and bigchaindb. Tendermint and mongodb synchronizes with the other nodes and runs without problems. Maybe not all files must be deleted, but it works.

**Comment by hectordufau** [comment]
@z3ky for restore transactions, this action requires another nodes, right?

And if you are testing and developing just one node and you want take a break of your job? Are all tested transactions lost?

I think your suggestion useful for recover a node. However, it continues as a bug for development.

**Comment by z3ky** [comment]
@hectordufau yes I use 4 nodes.
I shutdown 3 nodes as described above. On the 4th node, I just stop the services and do not delete the files. Thus, this node keeps all the transactions. I use the docker all in one image, so I just stop the container. Starting it again starts the bigchaindb and tendermint services. So far, this always worked without the mentioned error.

Maybe it has been fixed in bigchaindb 2.2.2 and is a regular behavior when trying to reconnect a node into a network.
