### ISSUE TITLE
Inconsistency of is_block_vaild on multiple machines.

### ISSUE THREAD

**Issue by jindragon** [bigchaindb/bigchaindb#319]
I'm running bigchaindb on 3 physical machines.
One main machine, and connected two other machines.
If I run the code on main machine, is_block_valid of bigchaindb console on main machine is true,
but is_block_valid on two other machines is fault. (both CREATE and TRANSFER)
I checked connection of rethinkdb, and there was no error.
What's the problem?

**Comment by r-marques** [comment]
What are the bigchaindb config files of each machine? Each node should have the public key of the other nodes in their keyring.

**Comment by jindragon** [comment]
I don't understant the meaning of 'Each node should have the public key of the other nodes in their keyring.'

I just used 'bigchaindb -y configure'.

If I enter 'bigchaindb show-config' on the main machine, I can see this.
![image](https://cloud.githubusercontent.com/assets/16792324/15386310/0fbfd6a4-1de2-11e6-8d95-a77989d4e67a.png)

If I enter same command on another one machine, I can see this.
![image](https://cloud.githubusercontent.com/assets/16792324/15386331/30976aea-1de2-11e6-832f-3178f2655859.png)

What should I do?

**Comment by r-marques** [comment]
If you want several bigchaindb instances to be part of the same federation they need to know about each other, and they to this through a public key. Each node as a public key and this key needs to be shared with the other nodes so you add the other nodes public keys in the keyring.

An example configuration for a 3 node federation would be:
- Node 1:
```json
{
    "api_endpoint": "http://localhost:9984/api/v1",
    "consensus_plugin": "default",
    "database": {
        "host": "localhost",
        "name": "bigchain",
        "port": 28015
    },
    "keypair": {
        "private": "3vvvycdbpJSeWkTpUaBQp7XxkyMVwUTYzFm9KvZUK275",
        "public": "Gjeoas6z3gnEu2Nr338k5k2UARWp997xnBxW3dcCEy8k"
    },
    "keyring": ["86FKgcihDAedKhz1DnLgpdVCdUfN6mKErSugkr1CDkmb", "HGKqCAqy1XY4h6B9Cy9FhUQtRF1VqpH6uQtJA9qnWVSR"],
    "server": {
        "bind": "localhost:9984",
        "threads": null,
        "workers": null
    },
    "statsd": {
        "host": "localhost",
        "port": 8125,
        "rate": 0.01
    }
}
```

- Node 2:
```json
{
    "api_endpoint": "http://localhost:9984/api/v1",
    "consensus_plugin": "default",
    "database": {
        "host": "localhost",
        "name": "bigchain",
        "port": 28015
    },
    "keypair": {
        "private": "A7HSXdrpStDowJButKxpXxsv6PBUfitooD6awoUiAbh6",
        "public": "86FKgcihDAedKhz1DnLgpdVCdUfN6mKErSugkr1CDkmb"
    },
    "keyring": ["Gjeoas6z3gnEu2Nr338k5k2UARWp997xnBxW3dcCEy8k", "HGKqCAqy1XY4h6B9Cy9FhUQtRF1VqpH6uQtJA9qnWVSR"],
    "server": {
        "bind": "localhost:9984",
        "threads": null,
        "workers": null
    },
    "statsd": {
        "host": "localhost",
        "port": 8125,
        "rate": 0.01
    }
}
```

- Node 3:
```json
{
    "api_endpoint": "http://localhost:9984/api/v1",
    "consensus_plugin": "default",
    "database": {
        "host": "localhost",
        "name": "bigchain",
        "port": 28015
    },
    "keypair": {
        "private": "6XjDSYbC3ewuBAFfzvJBaoFjR8iGCxC3aSyZbmt48SkL",
        "public": "HGKqCAqy1XY4h6B9Cy9FhUQtRF1VqpH6uQtJA9qnWVSR"
    },
    "keyring": ["Gjeoas6z3gnEu2Nr338k5k2UARWp997xnBxW3dcCEy8k", "86FKgcihDAedKhz1DnLgpdVCdUfN6mKErSugkr1CDkmb"],
    "server": {
        "bind": "localhost:9984",
        "threads": null,
        "workers": null
    },
    "statsd": {
        "host": "localhost",
        "port": 8125,
        "rate": 0.01
    }
}
```

Note that Node1 has Node2 and Node3 public keys in the keyring, Node2 has Node1 and Node3 public keys in the keyring and so on.

Since only federation nodes are able to create blocks if a node sees that a block was created by a node with a public key that does not belong to the federation it will vote the block invalid. This is why in your case the node that created the block marked the block as valid but the other two marked it as invalid because they did not know who the first node was (the node that created the block)

**Comment by jindragon** [comment]
Thank you what a kind man~
I fixed .bigchaindb file and solved the problem.
Thank you ^-'

**Comment by r-marques** [comment]
glad it solved the problem.
