### ISSUE TITLE
Ease the life of Windows users

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#34]
related: 

* http://bugs.python.org/issue2943
* https://github.com/pypa/pip/issues/942
* https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

**Comment by ttmc** [comment]
Initially, our focus will be on supporting BigchainDB Server for clusters/federations using Ubuntu and other popular Linux distributions (i.e. not Windows Server). That's simply because we only have so many developers within ascribe. If someone outside of ascribe wants to help by supporting Windows, they're welcome to do so.

As for BigchainDB clients, the initial client-server protocol will use HTTP(S), so one could write a client for just about any OS without too much trouble.

Therefore I will close this issue. A new issue can be opened e.g. if someone wants to build a Windows-specific client SDK.
