### ISSUE TITLE
Remove "operation" from transactions: not needed

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/bigchaindb#340]
We don't need the "operation" (which can be "CREATE" or "TRANSFER") in the [transaction data model](http://bigchaindb.readthedocs.io/en/latest/models.html#the-transaction-model). We can already figure out if a transaction is a creation or transfer transaction by checking to see if it has any inputs. (No inputs means it's a creation transaction.)

For the most part, I think the code already uses the number of inputs to figure out the transaction operation already, so this wouldn't require much change to the code.

**Comment by sonkesun** [comment]
I am trying to think of the best way to do this. We could easily make use of the checks that already exist in the transaction generation function (create_tx) in order to decide whether its a CREATE or a TRANSFER. But what about the "GENESIS" operation (transaction) required for the genesis block? One could think of generating functions (copy & paste) exclusively for this operation. I wonder what makes the GENESIS operation unique given the information provided in the transaction generation? Anyone have any thoughts?

**Comment by vrde** [comment]
In #444 we discuss the idea of removing the `GENESIS` operation. An idea to solve this issue is to focus just on the `CREATE` and `TRANSFER` operation, ignoring (for now) the `GENESIS` operation. We use RethinkDB, that is schemaless, so I think you can easily remove the `operation` key from the default transaction model, but keep it just for the `GENESIS` op.

Does this help you?

**Comment by sonkesun** [comment]
One way to solve this would be to overwrite the 'CREATE' operation only for the 'GENESIS' transaction and to update the transaction id (hash) with the new hash in the prepare_genesis_block function of util.py. 
The 'CREATE' and 'TRANSFER' operations can be set in create_tx depending on the input.  By doing this the operation would no longer be required for the create_transaction function and we keep the 'GENESIS' operation. What do you think?

**Comment by ttmc** [comment]
It seems we're keeping the `operation` in the transaction model for the foreseeable future, so I will 1) label this issue as `wontfix` and 2) close it.
