### ISSUE TITLE
Multiples nodes in a cluster

### ISSUE THREAD

**Issue by gekko68** [bigchaindb/bigchaindb#358]
Hi,
I have 4 nodes in my cluster and I can see in RethinkDB Admin UI that all 4 are connected to a cluster.

1.) How to I know that also BigchianDb communicates/votes in a cluster via all 4 nodes. I have added the 3 other public keys to the Keyring of each server. How can I test the setup ?

2.) What is your recommendation to setup replication and shards to scale out on each node ?

Unfortunately I can't find anything in the documentation on this topic 

BTW, each of the 4 nodes is an legally independent company and the server will be cross different countries 

Best, Michael

**Comment by r-marques** [comment]
You can check the votes in the block. The block document itself should contain the key `voters` with a list containing the 4 public keys of the nodes. And after a block as been voted you should see each node appending their vote to the block https://bigchaindb.readthedocs.io/en/latest/models.html#the-vote-model

Regarding sharding for best performance and data distribution you should set the sharding to the number of nodes in the cluster. You can do this using https://bigchaindb.readthedocs.io/en/latest/bigchaindb-cli.html#bigchaindb-set-shards. This only needs to be done once on a node since the configuration change replicates through the cluster.

For replication it depends on the fault tolerance you want. You can find more information here https://rethinkdb.com/docs/failover/

**Comment by rhsimplex** [comment]
> BTW, each of the 4 nodes is an legally independent company and the server will be cross different countries

Nice =)

**Comment by ttmc** [comment]
I've started working on documentation about how to set up and run a decentralized BigchainDB federation (see Issue #331). It's a big topic so I decided to create a separate set of docs to cover it. I've started on those docs and hope to have the first bits live next week.

**Comment by lakxraju** [comment]
I have a similar question as @gekko68 . I created a RethinkDB cluster with 3 nodes. And I started bigchaindb in all the three nodes. When one of the nodes created a block, I could see only 2 votes even though there are 3 nodes in the RethinkDB cluster. And out of those two votes, one vote is positive and the other is negative vote. But it is supposed to be a valid block. Because of this, when I run get_owned_assets() method, it doesn't return anything. Am I missing something? Thanks in advance..

**Comment by r-marques** [comment]
A federation node is a done that is part of the bigchaindb cluster. A federation node has access to the database, can vote and is able to `CREATE` digital assets.

All other actors are just clients using the bigchaindb cluster to request the creation of digital assets and to transfer them owners. 

Each node in the federation needs to know about the other nodes that is why you need to add in the keyring the keys of the other federation nodes. In your case since one of your nodes does not know about the other (because it doesn't exist in its keyring) it marks the block as invalid.

There was a similar question earlier about the configuration of a bigchaindb federation https://github.com/bigchaindb/bigchaindb/issues/319#issuecomment-220261899
For more information about federations https://www.bigchaindb.com/whitepaper/

> and how to create a non-federation node
We are in the process of better separating the server and client code, writing a client driver for bigchaindb and finishing the http api. At this moment you need to use `Bigchain()` to query your data or use the HTTP API.

**Comment by lakxraju** [comment]
Thanks a lot.. Now it works perfectly.. :-)

**Comment by ttmc** [comment]
I updated and added to [the documentation](https://bigchaindb.readthedocs.io/en/latest/clusters-feds/index.html) so now it explains more about how to set up a federation, including keyring, sharding and replication.
