### ISSUE TITLE
Make the configuration easier for docker-based setup

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#36]
Since containers are ephemeral, the config file that gets created under `~/.bigchaindb` will be wiped out along with the container each time a new container is started.

We need a way to mount this file, or to only rely on environment variables, which would be probably easier.

**Comment by vrde** [comment]
A simple solution would be to [mount a **host file** as a data volume](https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-host-file-as-a-data-volume). We can rely on env vars as well, since they are supported by the [configuration module](https://github.com/bigchaindb/bigchaindb/blob/develop/bigchaindb/__init__.py#L27).

Do you have some resources to share on what's the best practice to manage config files with docker?

**Comment by sbellem** [comment]
Will close this now. 

@vrde Sorry for not replying. As of now, the docker-compose.yml file relies on a file that is mounted, as you suggested above.
