### ISSUE TITLE
What to do when a node creates another Genesis block?

### ISSUE THREAD

**Issue by vrde** [bigchaindb/bigchaindb#444]
Any node can at any time write a new Genesis Block. AFAIK this is wrong but it doesn't affect the correct behavior of the system.

Possible solutions are:
- delete the additional Genesis Block (but we want the `bigchain` table to be append only)
- remove the concept of Genesis Block and assume that the first block is the one with no `previous_block_id` in the voting table

Ideas?

**Comment by ttmc** [comment]
We can't allow for deletions from the bigchain table. Special cases are exploit opportunities.

When a node comes back after a crash, it doesn't have any idea what the "previous block" was (in its view of the bigchain table's changefeed), but that's no reason to conclude that the first block it sees is a Genesis block.

There can only be one valid Genesis block. We could use that fact. Any time a node is asked to vote on a Genesis block, it can query to see if there is any other existing valid Genesis block. If yes, then the new Genesis block can be voted invalid.

Why do we need a Genesis block, again?

**Comment by libscott** [comment]
> Why do we need a Genesis block, again?

I'm still figuring out how the code works in general, but it appears to me that there's has to be a mechanism to identify a _singular_first block, whether or not it be created especially for the purpose of being the `genesis` block. Otherwise, since there's no block height, what would stop nodes from creating and working on multiple independent chains?

If this problem could be solved, then the code could be simplified considerably. Most of the logic related to genesis would be encapsulated in the selection of the first block. Valid transaction operations would be CREATE and TRANSFER, and this too could be removed since a `CREATE` transaction can then be identified by the presence of an asset / lack of conditions.

**Comment by libscott** [comment]
Returning to this, do we still have an issue here?

It appears to me that there is an issue, but the issue is that we do not verify vote signatures in `Bigchain.get_last_voted_block`.

This method is only called at startup to know which block to resume from. So a node could be tricked into working on the wrong chain.

I'm going to suggest that we handle this issue using the firewall:

* Blocks invalid votes
* Block duplicate genesis block

Thoughts?

**Comment by r-marques** [comment]
At this point validation of data by the firewall is out of scope.

One way to solve this would be to update the transaction validation so that when a there is a genesis transaction it checks that it doens't already exist in the bigchain. If one already exists then the block is invalid.

**Comment by libscott** [comment]
Currently the genesis block doesn't get voted on. So, either:

* Genesis block has fixed ID, so DB will reject dupe

or

* Vote on GENESIS block and check there's only one

thoughts?

**Comment by ttmc** [comment]
> Genesis block has fixed ID, so DB will reject dupe

That seems like a nice idea, as it leverages the backend database's auto-deduping "feature," but I wonder how much code would have to change? (Today, we have a different way of identifying the Genesis block.) I suspect it might not be a lot of code; a `grep -ri "genesis"` could find all the relevant code quite fast.

**Comment by libscott** [comment]
I'm wondering if there any issue with malleability. But on the other hand. I'm still not sure what the genesis block is for. Why not just point to `'0' * 64` if no block exists?
