### ISSUE TITLE
Block schema validation

### ISSUE THREAD

**Issue by rhsimplex** [bigchaindb/bigchaindb#446]
as #275 but for blocks. Although, blocks can only be written by other nodes, they should be rejected without a vote if the structure is incorrect

**Comment by r-marques** [comment]
related to #311 

If a block is written with an invalid schema it should still be voted invalid, right?

**Comment by ttmc** [comment]
BigchainDB Server never validated the schema of a built block. It did that for votes, go figure. But none of that matters anymore, because BigchainDB Server _no longer builds blocks or votes_. That job is handled by the consensus engine used by BigchainDB 2.0; it is no longer the concern of BigchainDB Server. This is no longer an issue so I'm closing it.
