### ISSUE TITLE
Extremely SLOW transactions creation

### ISSUE THREAD

**Issue by cyberthrone3** [bigchaindb/bigchaindb#463]
@vrde @sbellem 
Hi! I have a problem here. The documentation says it's possible to perform 1 000 000 transactions per second.
However, this primitive code provides 130 trs per sec only :(
```
transactions = []
for i in range(1000000):
    tx = db.create_transaction(db.me, testuser1_pub, None, 'CREATE', payload=None)
    tx = db.sign_transaction(tx, db.me_private)
    transactions.append(db.validate_transaction(tx))
block = db.create_block(transactions)
block = db.validate_block(block)
db.write_block(block)
```
What am I doing wrong?
Thanks!

**Comment by r-marques** [comment]
Hi @cyberthrone3 

On the whitepaper we showed that with datastore that we chose to work with, rethinkdb, it was possible to achieve 1 million writes per second in a 32 node cluster (1000 blocks of 1000 transactions per second).

The bigchaindb layer adds a lot of overhead, specifically verifying signatures is a cpu intensive task.
We are currently finishing the refactor of our multiprocessing code and we will be releasing benchmarks showing around 100K tx/s in a 32 node cluster with 32 cores per node. The benchmark tests will come with instructions to reproduce the results https://github.com/bigchaindb/bigchaindb/issues/246

Regarding your code you are trying to create a huge 1 million transactions block, validating it in a single core and writing the block.

A better way to test the speed would be first start bigchaindb in a console
```bash
$ bigchaindb start
```

And generate transactions
```python
for i in range(1000000):
    tx = db.create_transaction(db.me, testuser1_pub, None, 'CREATE', payload=None)
    tx = db.sign_transaction(tx, db.me_private)
    db.write_transaction(tx)
```
You can get even better performance if you use multiple cores to generate and write transactions, and the value of tx/s should increase linearly with each node you add to the cluster.

For a more in-depth look at how bigchaindb has evolved since the whitepaper you can check our blog https://medium.com/the-bigchaindb-blog/bigchaindb-where-it-came-from-where-were-at-where-we-re-headed-5004a319e35f#.b0enqp9cj

**Comment by cyberthrone3** [comment]
@r-marques Thank you for the answer!
Actually, I planned to store data in huge blocks containing 50 000 000 transactions. As I can understand, creation of this kind of blocks depends on my CPU only and not on the amount of nodes.
Am I right?

**Comment by ttmc** [comment]
RethinkDB's [documentation says](http://docs.rethinkdb.com/2.0/limitations/), "While there is no hard limit on the size of a single document, there is a recommended limit of 16MB for memory performance reasons." A BigchainDB block is stored as a RethinkDB document, so you probably can't put 50 million transactions in a block.

The normal operating mode of BigchainDB is that clients send transactions to the cluster, and those transactions get bundled into blocks, maxxing out at 1000 transactions per block. That's not something clients have control over.

Can you explain why you want to stuff so many transactions in one block? I'm having a hard time imaging a reason.

**Comment by cyberthrone3** [comment]
@ttmc 
Thank you for the answer! Now I think it's better to create 50 000 blocks with 1000 transactions.
But the problem is that these blocks will be created in a few days because my CPU it too way slow :(

That's why I think it's not an option to use Bigchaindb for my purposes.

Thanks everybody!
"I'm having a hard time imaging a reason." - for example, for storage quantum states of a certain space.
