### ISSUE TITLE
Pick a name for python bigchaindb driver

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#543]
e.g.: 

* pybigchaindb
* bigchaindb-driver
* etc

**Comment by r-marques** [comment]
I like `bigchaindb-driver`, its straightforward.
Another option would be a shorter version `bdb-driver`

**Comment by ttmc** [comment]
With RethinkDB, the `rethinkdb` package is actually the Python driver, because there is no Python package for RethinkDB Server, because RethinkDB Server isn't written in Python.

We already have a `bigchaindb` package (on PyPI) and today it's _everything_: server, Python driver, and Python client. Of course, the plan is to separate the BigchainDB server from the Python driver. Most developers will never install the server package: they'll be writing applications, so they'll only need the Python driver (or another driver). My suggestion is therefore something like:

* `bigchaindb` as the Python driver (Python package), i.e. the most-used package
* `bigchaindb-server` as the server package
* Some name for the package/module of shared stuff, e.g. `bichaindb-common`, or `bigchaindb-shared`

See issue #312 where @vrde also suggested some names

**Comment by sohkai** [comment]
Closing since we've (more or less) picked a name for the Python driver (https://github.com/bigchaindb/bigchaindb-driver).
