### ISSUE TITLE
Remove the need for manual configuration

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#549]
**IMPORTANT**: **This is NOT for production environments.**

**Related**:  #49 -- fourth point

The goal of this ticket is to have a default configuration mechanism (to facilitate development, experimentation, etc) such that

``` bash
$ pip install bigchaindb
$ bigchaindb start
```

works "out of the box".

No environment variables needed, no need to edit a config file, etc.

Some early pointers:

~~\- [ ] Installing bigchaindb could install a default config file that would be read/loaded upon starting bigchaindb.~~
- [ ] A default pub/priv key pair can be generated on the fly if none is found.

**Comment by ttmc** [comment]
There's already a default set of BigchainDB config settings; you can see them in https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/__init__.py

The only thing that prevents `pip install bigchaindb` + `bigchaindb start` from working "out of the box" is that there is no public/private keypair (because there is no default keypair). Maybe rather than suggesting they generate one using `bigchaindb -y configure`, we could just do that for them? Maybe explain the situation and ask for permission (yes/no)?

**Comment by ttmc** [comment]
We (@sbellem and I) just discussed this a bit more and came up with the following solution:

Almost all configuration settings already have default values (see https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/__init__.py ). The only exceptions are the public key and the corresponding private key.

If someone runs `bigchaindb start` and either the public key or private key don't have values (i.e. not set), then:
* Tell the user that a complete key pair was not found
* Auto-generate a new temporary key pair on-the-fly
* Don't put that key pair in `~/.bigchaindb`, just let it live in memory for the duration of the run
* Maybe put the auto-generated key pair in a file named `auto-generated_key_pair_<random number>` and tell the user about that file, in case they want to re-run with the same key pair in the future. (They should move the key pair out of that file to environment variables or a proper local config file.)

**Comment by sohkai** [comment]
+∞ for making dockerized people's lives infinitely easier.
