### ISSUE TITLE
Remove duplicate code from python server docs

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/bigchaindb#637]
Related to #607 

For this page: https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-server-api-examples.html
We have the markdown file itself:
- https://github.com/bigchaindb/bigchaindb/blob/master/docs/source/drivers-clients/python-server-api-examples.md

but additionally, we also have a Python file that can be run to _test_ the code examples in the markdown file:
- https://github.com/bigchaindb/bigchaindb/blob/master/tests/doc/run_doc_python_server_api_examples.py

As updating both files when making changes to the BigchainDB API is quite elaborate, it would be nice if we could:
- run the tests somehow against the .md file
- extract the python code snippets automatically from the file and test directly against them

/cc @ttmc: Maybe you explored this already?

**Comment by ttmc** [comment]
Issue #607 is about the same example code, but it's concerned with keeping the output up-to-date.

**Comment by ttmc** [comment]
I discussed the Python Server API examples page at

https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-server-api-examples.html

with Dimi (who wrote that page). He said that all the Python Server API functionality should (eventually) be exposed via the various client-side APIs, so that page will no longer be necessary. Maybe it can be moved to the Appendices, with some notes added to the top.

The corresponding tests in:

https://github.com/bigchaindb/bigchaindb/blob/master/tests/doc/run_doc_python_server_api_examples.py

can probably be deleted.
