### ISSUE TITLE
Master node compromise?

### ISSUE THREAD

**Issue by MMJ7** [bigchaindb/bigchaindb#644]
what will happen if the master node of the NoSQL database (RethinkDB) is compromised?

**Comment by r-marques** [comment]
What do you mean exactly with master node?

In BigchainDB there are no master nodes. All nodes are equal.
What can be done in case a node is compromised depends on the level of compromise.
Regarding the BigchainDB consensus layer a compromised node should not be able to alter the decision of a consensus round. We use a voting based consensus to reach quorum.
In terms of transactions a node only knows about its private key so it would not be able to create transactions with assets it does not own.
Regarding the actual data being stored in some situations a node would still be able to alter or delete data. We are working on a solution to prevent that from happening https://github.com/bigchaindb/bigchaindb/issues/594 so that we can have an append only database.

Does this answer your question?

**Comment by MMJ7** [comment]
Thank you. This answers my question to a lot of extend. What if a node alter the data stored in it and then propagate it to it's replica containing nodes too. As the wire protocol firewall only stops delete or drop not some sort of data alteration

**Comment by ttmc** [comment]
The wire protocol firewall will stop many other kinds of operations, including changes to documents in the bigchain and votes tables.

**Comment by MMJ7** [comment]
Thank you
