### ISSUE TITLE
[test] provide a test mode for server in which blocks are quickly valid

### ISSUE THREAD

**Issue by sbellem** [bigchaindb/bigchaindb#681]
The idea is to be able to run a BigchainDB node for testing and development purposes in such a way that block creation of valid transactions happens quickly.

At the moment, we need to put `sleep` statements in order to wait for a transaction to make it to a block that is vote upon to be valid.
### Ideas

Please feel free to add your idea here:
- Have a parameter such that voting is disabled, or by-passed, or sped up.
- etc

**Comment by r-marques** [comment]
Anything that requires io will always be difficult to predict how long it will take.

For a single db operation you can use `durability=hard` this will make the call block until the data is actually committed to disk so any read after that will succeed. But if you are testing something that requires several db operations this is no longer true.

Another solution that is used in several tests already is you create the transaction and instead of writing it to the backlog you create the block and write the block, and then write a vote that is `True`.
This would work for everything except it you are actually testing the voting code.

Another more time consuming solution is mocking the database operations in some cases.
