### ISSUE TITLE
Rename `data_id` in the Metadata and Asset models

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#717]
_From @r-marques on October 10, 2016 15:25_

I find the name `data_id` confusing in both the `Metadata` and `Asset` model.
Since they are already inside a namespace I propose to rename `data_id` to `id`.
This way we have:
- `Transaction.id`
- `Transaction.metadata.id`
- `Transaction.asset.id`

_Copied from original issue: bigchaindb/bigchaindb-common#39_

**Comment by r-marques** [comment]
_From @libscott on October 17, 2016 8:59_

I had a thought on this earlier, it might be good to design the naming of hashes in such a way that distinguishes between UUIDs and fingerprints, seeing as they are different and have different use cases, but can sometimes be confused (see for example #43). It's maybe not a big problem right now, but if we're going to change it we could use `[metadata|asset].uuid`.

edit: uuid would be even better

**Comment by r-marques** [comment]
_From @sbellem on October 17, 2016 9:44_

As an aside, we may want to consider using a different name than `id` since it is Python built-in function. It would leave no chance for ambiguity to arise.

**Comment by sohkai** [comment]
@r-marques Since you're working on some naming issues with the models right now, this could also be considered.

**Comment by r-marques** [comment]
I can handle this separately.
Trying to reduce the scope of the issues.

**Comment by ttmc** [comment]
@libscott had alternative idea in issue #697: instead of using separate IDs for transactions, assets, and metadata documents, just use transaction IDs for them all:

* To uniquely identify a specific asset, you can use the `id` of the CREATE Transaction where that asset first appeared
* To uniquely identify a specific metadata document, you can use the `id` of the Transaction containing that metadata document
