### ISSUE TITLE
Allow hashlock fulfillment creation in a TRANSFER

### ISSUE THREAD

**Issue by r-marques** [bigchaindb/bigchaindb#725]
_From @TimDaub on September 23, 2016 8:24_

Currently `Transaction.transfer` does not support creating hashlocks as fulfillments or conditions.

_Copied from original issue: bigchaindb/bigchaindb-common#19_

**Comment by ttmc** [comment]
A reminder: we need to be careful to ensure that every transaction gets signed at least once. If all the inputs to a TRANSFER transaction are fulfilling hashlocks (i.e. no signature conditions), then the TRANSFER transaction wouldn't be signed. That has to be fixed somehow. Ideas that I remember include:

1. Require every transaction to be signed by its "submitter" (who would also have to include their public key in a new transaction field).
2. Require at least one signature in the inputs somehow. (This is not as easy as it might seem, since crypto-conditions can be quite complex, e.g. consider this one:  `hashlock1 OR (signature1 AND hashlock2)` --- it could be fulfilled by hashlock1 alone.)
