### ISSUE TITLE
Performance of get_owned_ids

### ISSUE THREAD

**Issue by roderik** [bigchaindb/bigchaindb#787]
Extract from Gitter:

> **Roderik van der Veer @roderik Nov 02 20:29**:
> Is anyone experiencing very slow “get_owned_ids”? I've got 5 addresses with combined 80 assets in them, and when i do get_owned_ids on each of them (concurrently) i still end up with about 4.5 seconds to get all the results back. This would totally suck if i put in 100k assets 
I’m still on 0.6 btw

> **Rodolphe Marques @r-marques 09:22**:
> @roderik can you open a github issue. We should consider creating a secondary index for this query

**Comment by roderik** [comment]
Is there any update on this? I've run out of options with some 600 assets...

**Comment by r-marques** [comment]
@roderik currently working on it. I will cc you when I make the pull request

**Comment by r-marques** [comment]
#1125 Added secondary indexes for inputs and outputs which makes the database queries faster, and the execution time pretty much constant as the number of documents grow since we no longer perform full table/collection scans for those queries.

We still have a performance bottleneck in `get_owned_ids` because for each transaction that the database returns we still need to check the `votes` table to see if the transaction is on a valid block.
We are still looking at solutions for this and we have a task on the rodmap to address the performance issues of all the queries.

**Comment by ttmc** [comment]
@roderik We recognize that it's important to make this query fast. We haven't forgotten! BigchainDB 2.0 works very differently and is coming out very soon. We have good reason to expect that this query will run much faster in BigchainDB 2.0. For one, there are no more invalid blocks to go through and weed out! We'll be doing some performance benchmarking soon after the release of 2.0, and then we'll _know_ how fast it is, and we can start figuring out how to make it even faster.
