### ISSUE TITLE
Revisit "inner" transaction in transaction model

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/bigchaindb#828]
Having an "inner" transaction inside the transaction model seems to be confusing and redundant:

```
tx = {
    'id': '…',
    'transaction': {
        …
    }
    …
}
```

From talks with @ttmc, @sbellem, @libscott.

**Comment by sbellem** [comment]
My current understanding of the inner `dict` is that it is a way to identify the data used for the message for signature -based fulfillments..

I also think it is redundant in a way. On the other hand, to be able to grab the `dict` needed to create the signature via one key is useful.

Perhaps, we could consider reviewing the name of the key?

**Comment by ttmc** [comment]
The original reason for the inner `transaction` (transaction body) dict was so that a Transaction would have a structure of the form {id, body, signature}, where id and signature are functions of the body. That's how blocks are structured too.

If you look at the code for signing a transaction (i.e. the `sign()` method in the `Transaction` class, in `bigchaindb/common/transaction.py`), you'll see that it doesn't use the inner `transaction` dict at all. It builds each dict-to-sign (for each fulfillment) out of the Transaction object's pieces such as `self.operation`, `self.asset`, and `self.version` (which isn't even inside the inner `transaction` dict).

As far as I can tell, we could get rid of that inner `transaction` dict (keeping its contents, of course). It's useless historical baggage from the days before the `Transaction` class (i.e. the days when dicts were passed around and worked with directly).

**Comment by sbellem** [comment]
Ok, then. 

> Flat is better than nested.

**Comment by libscott** [comment]
Anyone have thought? @r-marques, @diminator, @vrde ?

**Comment by vrde** [comment]
> Anyone have thought?

I like this.

**Comment by diminator** [comment]
something like this then?
```
{
    "id": "<hash of transaction, excluding signatures (see explanation)>",
    "version": "<version number of the transaction model>",
    "fulfillments": ["<list of fulfillments>"],
    "conditions": ["<list of conditions>"],
    "operation": "<string>",
    "asset": "<digital asset description (explained in the next section)>",
    "metadata": {
         "id": "<uuid>",
         "data": "<any JSON document>"
    }
}
```

**Comment by libscott** [comment]
> something like this then?

Yep: https://github.com/bigchaindb/bigchaindb/blob/4de3d83a56ef8849b369c3e2b61212ed365d8a83/bigchaindb/common/schema/transaction.yaml#L9
